feature: Метка
type: Персонализация ("Tas-ix для Узбекистана")

specs:
  aliases:
  - &CheckMetrics
    - assertMetrics:
      - web.total_request_count
      - web.total_click_count
      - web.total_dynamic_click_count
      - web.abandonment
      - web.total_all_click

  В рекламе:
    - params:
        foreverdata: '782294899'
        tld: 'uz'
        lr: '10335'
        noredirect: '1'
        srcparams: 'UPPER=rearr=scheme_Local/HighlightDocuments/UserConfig=uz_testing_white;UPPER=rearr=scheme_Local/HighlightDocuments/UseKuub=1'
    - do: получить выдачу по запросу 'kino tasix'
    - assert: рекламный сниппет с меткой 'Tas-ix' присутствует на странице
    - screenshot: внешний вид [plain]
    - do: навести курсор на метку
    - assert: появился тултип
    - screenshot: вид сниппета с меткой и тултипом [hover]
    - tech: сработал счетчик path = '/$page/$main/$result[@type="adv"]/tas-ix'
    - *CheckMetrics

  В органике:
    - params:
        foreverdata: '1142140074'
        tld: 'uz'
        lr: '10335'
        noredirect: '1'
        srcparams: 'UPPER=rearr=scheme_Local/HighlightDocuments/UserConfig=uz_testing_white;UPPER=rearr=scheme_Local/HighlightDocuments/UseKuub=1'
    - do: получить выдачу по запросу 'kino tasix'
    - assert: рекламный сниппет с меткой 'Tas-ix' присутствует на странице
    - screenshot: внешний вид [plain]
    - do: навести курсор на метку
    - assert: появился тултип
    - screenshot: вид сниппета с меткой и тултипом [hover]
    - tech: сработал счетчик path = '/$page/$main/$result[@type="organic"]/tas-ixl'
    - *CheckMetrics

files:
  - features/desktop/adapter-recommendation-label/__tas-ix/adapter-recommendation-label__tas-ix.hermione.js

tags:
  - reviewed

v-team: Beauty

tlds: uz
