feature: Афиша события (touch-phone)
experiment: Колдунщик на реакте
counter: /$page/$main/$result[@wizard_name="afisha_event"]/afisha_event/title

specs:
  params:
    lr: '213'
    rearr:
      - 'scheme_Local/PrettySerpFeatures/ForbiddenFeatures/afisha_events_landings=1'
      - 'scheme_Local/PrettySerpFeatures/ForcedFeatures/afisha_events_testing_landings=1'

  Проверка счётчиков:
    - do: получить выдачу по запросу 'артик и асти'
    - assert: в результатах выдачи появился колдунщик афиши
    - do: кликнуть по тайтлу
    - assert: открылся сервис Яндекс.Афиша с информацией про концерт
    - tech: сработал счетчик path='/$page/$main/$result[@wizard_name="afisha_event"]/afisha_event/title'
    - do: кликнуть по гринурлу
    - assert: открылся сервис Яндекс.Афиша с информацией про концерт
    - tech: сработал счетчик path='/$page/$main/$result[@wizard_name="afisha_event"]/afisha_event/path/urlnav'
    - do: кликнуть по картинке
    - assert: открылся сервис Яндекс.Афиша с информацией про концерт
    - tech: сработал счетчик path='/$page/$main/$result[@wizard_name="afisha_event"]/afisha_event/thumb'
    - do: кликнуть по кнопке "Билеты от ...", vars='source=wizard'
    - assert: осуществился переход на страницу https://widget.afisha.yandex.ru
    - tech: сработал счетчик path='/$page/$main/$result[@wizard_name="afisha_event"]/afisha_event/button'
    - assertMetrics:
        - web.total_request_count
        - web.total_click_count
        - web.total_all_click

  Внешний вид (продажа билетов):
    - do: получить выдачу по запросу 'артик и асти'
    - assert: в результатах выдачи появился колдунщик афиши
    - screenshot: внешний вид [concert]

  Внешний вид (продажа билетов - театр):
    - do: получить выдачу по запросу 'про федота стрельца'
    - assert: в результатах выдачи появился колдунщик афиши
    - screenshot: внешний вид [theatre]

  Внешний вид (билетов нет):
    - do: получить выдачу по запросу 'барокко гоголь центр'
    - assert: в результатах выдачи появился колдунщик афиши
    - screenshot: внешний вид [no_tickets]

tags:
  - skip_e2e_check
  - react
  - no_assessors
v-team: VanillaGeo
files:
  - src/features/AfishaEvent/AfishaEvent.test/AfishaEvent@touch-phone.hermione.js

tlds: all
