feature: Превью-объявлений

specs:
  Внешний вид:
    - params:
        text: '1'
        lr: '213'
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида [plain]
    - label: direct-preview-{{PLATFORM}}-{{BROWSER_TYPE}}
  Внешний вид с БНО:
    - tags:
        - BNO
    - params:
        text: '1'
        lr: '213'
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-with-bno-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида с БНО [bno]
  Внешний вид с дисклеймерами:
    - tags:
        - disclaimer
    - params:
        text: '1'
        lr: '213'
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-with-disclaimers-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида с дисклеймерами [disclaimers]
  Внешний вид комбинированный 1:
    - tags:
        - BNO
    - params:
        text: ''
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-mixed-1-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида с дисклеймерами [mixed-1]
  Внешний вид комбинированный 2:
    - tags:
        - disclaimer
    - params:
        text: ''
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-mixed-2-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида с дисклеймерами [mixed-2]
  Внешний вид комбинированный 3:
    - tags:
        - disclaimer
    - params:
        text: ''
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-mixed-3-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида с дисклеймерами [mixed-3]
  Внешний вид комбинированный 4:
    - tags:
        - BNO
        - disclaimer
    - params:
        text: ''
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-mixed-4-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида с дисклеймерами [mixed-4]

specs-integration:
  Базовое поведение:
    - do: заменить в ссылке /search/ на /search/direct-preview/
    - assert: проверить, что в выдаче есть рекламный сниппет

files:
  - features/direct-preview/direct-preview@common.hermione.js
  - features/direct-preview/direct-preview@common.hermione.e2e.js

tags:
  - no_assessors
  - skip_e2e_check
  - direct_preview

browsers:
  notFor:
    - searchapp-phone

v-team: Distribution

tlds:
  - ru
