feature: Одна организация
experiment: Скрытие блоков по формуле c бэкенда

specs:
  Популярные блоки скрыты:
    - params:
        exp_flags: GEO_1org_show_wizard_parts_by_backend_config=1
        foreverdata: '896288788'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе нет блока с текстовыми фичами (они же признаки)
    - assert: в карточке на главном табе нет блока публикаций
    - assert: в карточке на главном табе нет блока меню
    - assert: в карточке на главном табе нет блока похожих организаций
    - assert: в карточке на главном табе нет блока гистограммы посещаемости
  Популярные блоки показываются:
    - params:
        exp_flags: GEO_1org_show_wizard_parts_by_backend_config=1
        foreverdata: '3754793884'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе есть блок с текстовыми фичами (они же признаки)
    - assert: в карточке на главном табе есть блок публикаций
    - assert: в карточке на главном табе есть блок меню
    - assert: в карточке на главном табе есть блок похожих организаций
    - assert: в карточке на главном табе есть блок гистограммы посещаемости
  Врезка Недвижимости скрыта:
    - params:
        foreverdata: '733380778'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе есть блок с предложениями Недвижимости
  Врезка Автору скрыта:
    - params:
        foreverdata: '268370226'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе нет блока с предложеними Автору

files:
  - features/companies/experiments/GEO_1org_show_wizard_parts_by_backend_config/GEO_1org_show_wizard_parts_by_backend_config@desktop.hermione.js

browsers: chrome-desktop

v-team: VanillaGeo

tags:
  - skip_e2e_check

tlds: all
