Открытие настроек:
  - do: над списком чатов нажать на шестеренку (настройки)
  - assert: открылось модальное окно со списком настроек (пример внешнего вида https://jing.yandex-team.ru/files/apanichkina/Screen%20Shot%202019-05-22%20at%2011.04.23%20PM.png)
