feature: ProductListFilterScreen

specs:
    Внешний вид страницы фильтров:
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
        - do: Нажать на кноку Фильтры
        - screenshot: внешний вид соответствует скриншоту [filter-page]

    Проверка выбора фильтров:
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
        - do: Нажать на кноку Фильтры
        - do: Выбрать несколько параметров
        - screenshot: внешний вид соответствует скриншоту [filter-page]

    Выбор фильтров:
        Несколько в одной группе:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/vamvelosiped.ru/n/yandexturbocatalog/
            - do: нажать на кнопку "Фильтры"
            - do: в блоке "Цвет" выбрать "Бежевый"
            - do: запомнить цифру на кнопке "Показать N товаров"
            - do: в блоке "Цвет" выбрать "Белый" (именно Белый, а не Белая, Белые и т.п.)
            - assert: цифра на кнопке "Показать N товаров" изменилась
            - do: нажать на кнопку "Показать N товаров"
            - do: открыть карточку любого товара
            - do: в блоке "Характеристики" нажать на кнопку "Читать еще", если она есть
            - assert: в блоке "Характеристики" отображается "Цвет" со значением "Бежевый" или "Белый"
            - do: нажать на кнопку "Каталог" в левом верхнем углу
            - do: нажать на кнопку "Фильтры"
            - do: выбрать фильтра "Материал" = "Алюминий"
            - do: нажать на кнопку "Показать N товаров"
            - do: открыть карточку любого товара
            - do: раскрыть блок "Характеристики" по кнопке "Читать еще", если она есть
            - assert: в блоке "Характеристики" отображается "Цвет" со значением "Белый", "Материал" со значением "Алюминий"

    Проверка выбора фильтров через "показать все":
        - do: открыть страницу https://yandex.ru/turbo/super01.ru/n/yandexturbocatalog/
        - do: нажать на кноку Фильтры
        - do: нажать на кнопку "Показать все" под списком фильтров
        - screenshot: внешний вид соответствует скриншоту [filter-detail-page]
        - do: выбрать несколько соседних чекбоксов
        - screenshot: внешний вид выбранных пунктов соответствует скриншоту [selected-filters]
        - do: выбрать еще один чекбокс
        - do: нажать кнопку "Применить"
        - assert: открылась страница с фильтрами где выбранные чекбоксы отображабтся в начале списка
        - screenshot: внешний вид соответствует скриншоту [filter-page]

    "Выбор параметров основных фильтров: цена и бренд":
        - params:
            exp_flags:
                - turbo-app-main-filters-only=1
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
        - do: нажать на кнопку "Фильтры"
        - do: дождаться загрузки фильтров
        - screenshot: внешний вид фильтров соответствует скриншоту [non-selected-filters]
        - do: в блоке "Бренд" нажать по кнопке "Показать все"
        - screenshot: внешний вид соответствует скриншоту [filter-detail-page]
        - do: отметить пункт "aute reprehenderit deserunt"
        - do: отметить пункт "cillum"
        - screenshot: внешний вид выбранных фильтров соответствует скриншоту [selected-filters]
        - do: нажать на кнопку "Применить"
        - assert: произошел переход на экран с компактным видом фильтра по брендам
        - do: отметить пункт "Lorem"
        - screenshot: внешний вид фильтров соответствует скриншоту (с учетом порядка брендов) [filter-page]
        - do: дождаться загрузки числа товаров на кнопке внизу экрана
        - do: кликнуть по кнопке внизу, подпись на которой начинается с "Показать"
        - tech: в консоли значение window.location.pathname равно '/turbo/spideradio.github.io/n/yandexturbocatalog/'
        - tech: в get-параметрах есть параметр 'filters' со значением "v%3A1%2C13%2C10"

    Внешний вид при переходе с листинга:
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/?category_id=9
        - do: нажать на кноку «Фильтры»
        - assert: внешний вид соответствует скриншоту [https://jing.yandex-team.ru/files/skurhanski/chrome_L83pW2EotI.png]

    Внешний тултипа фильтров:
        - automation: TURBOUI-5850
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
        - do: нажать на кноку 'Фильтры'
        - do: в блоке Цена указать до 3000, в блоке Сиденье - Не стандартный, Цвет стула - Белый, Цвет каркаса - Черный и нажать 'Показать'
        - assert: рядом (не на расстоянии) с кнопкой 'Фильтры' отображается тултип с цифрой '4' [https://jing.yandex-team.ru/files/skurhanski/chrome_R07m4777F8.png]
        - do: повернуть устройство в ландшафтную ориентацию
        - assert: положение тултипа относительно кнопки 'Фильтры' не изменилось

    Сохраняются при переходе:
        С каталога на страницу категории:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/mytoys.ru/n/yandexturbocatalog/
            - do: нажать на кноку 'Фильтры'
            - do: выбрать фильтр "Пол" = "Женский"
            - do: кликнуть "Показать N товаров"
            - do: кликнуть в любую категорию
            - do: открыть карточку любого товара из категории
            - do: в блоке "Характеристики" нажать на кнопку "Читать еще", если она есть
            - assert: в блоке "Характеристики" отображается "Пол" со значением "Женский"
        С каталога на вторую страницу каталога:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/muztorg.ru/n/yandexturbocatalog/
            - do: кликнуть на кнопку "Фильтры"
            - do: выбрать фильтр "Материал топа" = "Агатис"
            - do: кликнуть "Показать N товаров"
            - do: проскроллить до второй страницы, надо чтобы появились заглушки на короткое время
            - do: открыть карточку любого товара на загрузившейся странице
            - do: в блоке "Характеристики" нажать на кнопку "Читать еще", если она есть
            - assert: в блоке "Характеристики" отображается "Материал топа" со значением "Агатис"
        С категории на вторую страницу категории:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/muztorg.ru/n/yandexturbocatalog/
            - do: перейти категорию "Гитары"
            - do: кликнуть на кнопку "Фильтры"
            - do: выбрать фильтр "Материал топа" = "Агатис"
            - do: кликнуть "Показать N товаров"
            - do: проскроллить до второй страницы, надо чтобы появились заглушки на короткое время
            - do: открыть карточку любого товара на загрузившейся странице
            - do: в блоке "Характеристики" нажать на кнопку "Читать еще", если она есть
            - assert: в блоке "Характеристики" отображается "Материал топа" со значением "Агатис"
        С каталога на страницу поиска:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
            - do: кликнуть на кнопку "Фильтры"
            - do: выбрать фильтр "Цвет каркаса" = "Черный"
            - do: нажать на кнопку "Показать 1 товар"
            - do: в поле поиска вверху страницы ввести "порядка"
            - do: нажать на кнопку "Найти"
            - assert: |
                в списке товаров отображается один товар
                на кнопке "Фильтры" отображается счетчик "1"
                в урле есть параметр "filters=p3%3A1"
        С категории на страницу поиска:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/mebelion.ru/n/yandexturbocatalog/
            - do: кликнуть в любую категорию
            - do: кликнуть на кнопку "Фильтры"
            - do: выбрать фильтр "Гарантия, месяцы" = "12", если отображается кнопка "Показать 0 товаров", выбрать другую категорию
            - do: кликнуть "Показать N товаров"
            - do: в поле поиска ввести слово "лампа"
            - do: нажать кнопку "Найти"
            - assert: на кнопке "Фильтры" отображается счетчик "1"
            - do: открыть карточку любого товара
            - assert: в характеристиках товара отображается "Гарантия, месяцы" со значением 12
        С карточки товара на каталог:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/mnogomeb.ru/n/yandexturbocatalog/
            - do: кликнуть на кнопку "Фильтры"
            - do: выбрать фильтр "Тип товара" = "Банкетка"
            - do: нажать на кнопку "Показать N товаров"
            - do: открыть любую карточку из отобранных товаров
            - do: нажать кнопку "Читать еще" в разделе "Характеристики"
            - assert: в разделе "Характеристики" отображается "Тип товара" = "Банкетка"
            - do: нажать на кнопку "Каталог" в левом верхнем углу карточки товара
            - assert: |
                на кнопке фильтры отображается счетчик "1"
                в списке отображаются товары с типом товара банкетка

    Работают вместе с:
        Сортировкой, поиском и ценой:
            - automation: TURBOUI-5954
            - do: открыть страницу https://yandex.ru/turbo/mnogomeb.ru/n/yandexturbocatalog/
            - do: нажать на кнопку "Фильтры"
            - do: в блоке "Тип товара" выбрать "Банкетка"
            - do: нажать на кнопку "Показать N товаров" внизу страницы
            - do: нажать на кнопку сортировки, по умолчанию она отображается как "По популярности"
            - do: выбрать "Сначала дешевле"
            - assert: товары отсортированы по возрастанию цены
            - do: открыть любую карточку товара
            - assert: в разделе "Характеристики" отображается "Тип товара" = "Банкетка" (возможно, потребуется нажать на "Читать еще" для раскрытия полного списка характеристик)
            - do: нажать на кнопку "Каталог" в левом верхнем углу карточки товара
            - do: в поле поиска ввести "бежевый"
            - do: нажать "Найти"
            - assert: |
                в списке товаров в каждой карточке присутствует слово "бежевый" (и его производные) в названии
                на карточке любого товара из списка в характеристиках отображается "Тип товара" = "Банкетка"
            - do: нажать на кнопку "Фильтры"
            - do: в диапозон цен ввести 5000 - 7000
            - do: нажать на кнопку "Показать N товаров"
            - assert: |
                отображаются только товары с "бежевый" (и его производные) в названии
                отображаются товары стоимостью 5000 - 7000р
                на карточке любого товара из списка в характеристиках отображается "Тип товара" = "Банкетка"
            - do: выбрать сортировку "Сначала дороже"
            - assert: товары отсортированы по убыванию цены
            - do: выбрать сортировку "По скидке"
            - assert: первыми отображаются товары со скидкой (если таковые имеются)

files:
  - screens/ProductListFilterScreen/__tests__/ProductListFilterScreen@phone.hermione.js

tags:
  - ecom-tap
  - filters

tlds: ru

v-team: Turbo
