feature: ProductPage
experiment: Навигация по SKU

params:
  exp_flags:
    - PRODUCTS_card_enable_navigation=1

specs:
  beforeEach:
    - do: открыть https://yandex.ru/products/product/1414986413/sku/101446177753.
    - assert: открылась карточка товара.
    - do: проскролить страницу до блока навигации.
    - assert: в карточке присутствует блок навигации.
  Внешний вид:
    - label: sku-navigation_{{PLATFORM}}
    - screenshot: пример внешнего вида навигации. По смыслу элементы навигации могут отличаться от тех что в примере. Некоторые элементы могут быть неактивны. [navigation]
  Внешний вид кнопки развертывания скрытых элементов навигации:
    - tags:
        - no_assessors # кнопка развертывания скрытых элементов навигации не всегда есть есть в проде
    - label: sku-navigation-more-button_{{PLATFORM}}
    - screenshot: пример внешнего вида навигации. По смыслу элементы навигации могут отличаться от тех что в примере. Некоторые элементы могут быть неактивны. [sku-navigation_{{PLATFORM}} >> navigation]
    - do: проскролить страницу чтобы был виден конец блока навигации.
    - assert: |
        виден конец блока навигации.
        внизу блока навигации может присутствовать кнопка развертывания скрытых элементов навигации с текстом содержащим названия скрытых элементов навигации.
    - screenshot: пример внешнего кнопки развертывания скрытых элементов навигации. Надпись на кнопке контекстно зависима и может не совпадать с примером [navigation-more-button]
  Выбор элемента навигации:
    - screenshot: пример внешнего вида навигации. По смыслу элементы навигации могут отличаться от тех что в примере. Некоторые элементы могут выглядить как неактивны. [sku-navigation_{{PLATFORM}} >> navigation]
    - do: проскролить страницу чтобы был виден конец блока навигации.
    - assert: |
        виден конец блока навигации.
        внизу блока навигации может присутствовать кнопка развертывания скрытых элементов навигации с текстом содержащим названия скрытых элементов навигации.
    - screenshot: пример внешнего кнопки развертывания скрытых элементов навигации. Надпись на кнопке контекстно зависима и может не совпадать с примером [sku-navigation-more-button_{{PLATFORM}} >> navigation-more-button]
    - do: нажать на кнопку развертывания скрытых элементов навигации с текстом содержащим названия скрытых элементов навигации, если она присутствует внизу блока навигации.
    - assert: |
        внизу блока навигации отсутствует кнопка развертывания скрытых элементов навигации.
        показан полный список доступных элементов навигации.
    - do: нажать на любой из элементов навигации.
    - assert: |
        в карточке отобразились данные соответствующие выбранному элементу. Активные элементы навигации могут измениться. Некоторые элементы навигации могут стать неактивными.
        страница не отскролилась наверх. В некоторых случаях позиция прокрутки может измениться на небольшое значение из-за другого размера картинок.
        содержимое страницы поменялось и соответствует выбраному элементу навигации.
        количество групп навигации не поменялось. Некоторые элементы навигации могут выглядить как неактивные.

v-team: goods

files:
  - src/pages/ProductPage/tests/exp/ProductPage_withNavigation.touch.hermione.ts
