feature: ProductPage
experiment: Ракурсы

specs:
  beforeEach:
    - params:
      exp_flags:
        - PRODUCTS_desktop_preview_gallery=1
    - do: открыть https://yandex.ru/products/search?text=iphone
    - assert: отобразилась страница с результатами поиска по товарам
    - do: открыть первую карточку
    - assert: |
        в открывшейся карточке с товаром находится большая картинка товара
        под большой картинкой находится блок с миниатюрами - маленькими картинками этого товара в других ракурсах

  Внешний вид:
    - assert: первая миниатюра оформлена как активная (обведена рамкой)
    - screenshot: внешний вид [first-active]

  Переключение по наведению:
    - assert: в блоке ракурсов не меньше 3х картинок
    - do: навести курсор мыши на вторую картинку миниатюру в блоке ракурсов и не кликать
    - assert: |
        вторая картинка в блоке с миниатюрами стала активна (обведена рамкой)
        большая картинка товара переключилась на изображение, соответствующее второй миниатюре в блоке ракурсов
    - screenshot: внешний вид [hovered-second]
    - do: навести курсор мыши на третью картинку миниатюру в блоке ракурсов и не кликать
    - assert: |
        третья картинка в блоке с миниатюрами стала активна (обведена рамкой)
        большая картинка товара переключилась на изображение, соответствующее третьей миниатюре в блоке ракурсов
    - do: навести курсор мыши на большую картинку
    - assert: |
        большая картинка переключилась на изначальное состояние - первую картинку
        в блоке ракурсов также первая картинка стала активной

  Переключение по клику:
    - assert: в блоке ракурсов не меньше 3х картинок
    - do: навести курсор мыши и кликнуть на третью картинку миниатюру в блоке ракурсов
    - assert: |
        третья картинка в блоке с миниатюрами стала активна (обведена рамкой)
        большая картинка товара переключилась на изображение, соответствующее третьей миниатюре в блоке ракурсов
    - do: навести курсор мыши на вторую картинку миниатюру в блоке ракурсов и не кликать
    - assert: |
        вторая картинка в блоке с миниатюрами стала активна (обведена рамкой)
        большая картинка товара переключилась на изображение, соответствующее второй миниатюре в блоке ракурсов
    - do: навести курсор мыши на большую картинку
    - assert: |
        большая картинка переключилась на третью картинку из блока ракурсов
        в блоке ракурсов также третья картинка стала активной

v-team: goods

files:
  - src/pages/ProductPage/tests/exp/ProductPage_withThumbPreview.desktop.testpalm.yml
