feature: ProductPage

specs:
  Поиск:
    - do: открыть /products/offer/X6Ha41qz5hqDe5B_YDphiQ?promo=nomooa
    - assert: поисковая строка пустая (не учитывая placeholder - текст-подложку)
    - do: ввести в поисковую строку запрос «iphone»
    - do: нажать на кнопку «Найти»
    - assert: появилась поисковая выдача
    - assert: урл имеет путь "/products/search" и cgi-параметр "text", равный "iphone"

    Нажатие на крестик без поискового запроса:
      - do: открыть https://yandex.ru/products/product/824253112
      - assert: |
          открылась страница модели
          на изображении товара присутствует крестик
      - do: нажать на крестик в верхнем правом углу
      - assert: произошел переход на выдачу по запросу "Холодильники"

    Нажатие на крестик c поисковым запросом:
      - do: открыть https://yandex.ru/products/product/824253112?text=iphone
      - assert: |
          открылась страница модели
          на изображении товара присутствует крестик
      - do: нажать на крестик в верхнем правом углу
      - assert: произошел переход на выдачу по запросу "iphone"

  SKU:
    Нажатие на крестик без поискового запроса:
      - do: открыть https://yandex.ru/products/product/752262035/sku/101100443755
      - assert: |
          открылась страница SKU
          на изображении товара присутствует крестик
      - do: нажать на крестик в верхнем правом углу
      - assert: произошел переход на выдачу по запросу "Мобильные телефоны"

    Нажатие на крестик c поисковым запросом:
      - do: открыть https://yandex.ru/products/product/752262035/sku/101100443755?text=iphone
      - assert: |
          открылась страница SKU
          на изображении товара присутствует крестик
      - do: нажать на крестик в верхнем правом углу
      - assert: произошел переход на выдачу по запросу "iphone"

    Переход к форме "Подписка на снижение цены":
      - params:
          exp_flags:
            - price_trend_redesign=1
            - price_charts_enabled=1
            - sku_subscriptions_enabled=1
            - enable_price_subscription=1
            - enable_price_subscription_unauthorized=1
      - do: открыть https://yandex.ru/products/product/752262035/sku/101100443755#price_subscription под авторизованным пользователем
      - assert: |
          открылась страница товара
          страница товара автоматически прокрутилась до секции "Динамика минимальной цены" с графиком изменения минимальной цены
          открылось всплывающее окно "Подписка на снижение цены"

  Оффер:
    Нажатие на крестик без поискового запроса:
      - do: открыть https://yandex.ru/products/offer/X6Ha41qz5hqDe5B_YDphiQ
      - assert: |
          открылась страница оффера
          на изображении товара присутствует крестик
      - do: нажать на крестик в верхнем правом углу
      - assert: произошел переход на выдачу по запросу "Мобильные телефоны"

    Нажатие на крестик c поисковым запросом:
      - do: открыть https://yandex.ru/products/offer/X6Ha41qz5hqDe5B_YDphiQ?text=iphone
      - assert: |
          открылась страница оффера
          на изображении товара присутствует крестик
      - do: нажать на крестик в верхнем правом углу
      - assert: произошел переход на выдачу по запросу "iphone"

  Metrics:
    Запросы:
      - tags:
          - no_assessors
      - do: открыть https://yandex.ru/products/product/1414986413/sku/101446177753
      - assert: открылась карточка товара
      - do: кликнуть на крестик закрытия карточки товара
      - tech: |
          - метрика "products.all_requests" = 2
          - метрика "products.sku_requests" = 1
          - метрика "products.requests" = 1
      - do: нажать на первую карточку товара
      - assert: открылась страница с товаром
      - tech: |
          - метрика "products.all_requests" = 3
          - метрика "products.sku_requests" = 2
          - метрика "products.requests" = 1

    Главная → Выдача → SKU → Внешний магазин:
      - tags:
          - no_assessors
      - do: открыть https://yandex.ru/products/
      - assert: открылась главная страница
      - do: кликнуть на первую категорию товаров
      - assert: открылась страница выдачи
      - do: открыть первый SKU на выдаче
      - assert: открылась страница SKU
      - do: кликнуть по ссылке первого магазина
      - tech: |
          - метрика "products.requests" = 1
          - метрика "products.product_card_sku_clicks" = 1
          - метрика "products.product_card_clicks" = 1
          - метрика "products.sku_requests" = 1
          - метрика "products.sku_external_clicks" = 1
          - метрика "products.sku_total_clicks" = 1
          - метрика "products.total_clicks" = 1
          - метрика "products.all_requests" = 2
          - метрика "products.all_external_clicks" = 1

    Выдача → Оффер → Внешний магазин:
      - tags:
          - no_assessors
      - do: открыть https://yandex.ru/products/search?text=рубашка%20в%20полосочку
      - assert: открылась страница выдачи
      - do: открыть первый оффер на выдаче
      - assert: открылась страница оффера
      - do: кликнуть по ссылке первого магазина
      - tech: |
          - метрика "products.requests" = 1
          - метрика "products.product_card_offer_clicks" = 1
          - метрика "products.product_card_clicks" = 1
          - метрика "products.offer_requests" = 1
          - метрика "products.offer_external_clicks" = 1
          - метрика "products.offer_total_clicks" = 1
          - метрика "products.total_clicks" = 1
          - метрика "products.all_requests" = 3
          - метрика "products.all_external_clicks" = 1

  Проверенный магазин:
    params:
      exp_flags:
        - trusted_merchant_icon=1

    Страница оффера:
      - tags:
          - no_assessors
      - do: открыть https://yandex.ru/products/offer/vGHLX0Xlkk8XUXhqK1dvhQ
      - screenshot: внешний вид блока с предложениями магазинов соответствует скриншоту [inactive-layout]
      - tech: в baobab-дереве залогирован узел по пути '$page.$main.card.feedbackMode'
      - do: кликнуть на иконку "Проверенный магазин"
      - assert: появился попап с описанием того, что означает иконка
      - screenshot: внешний вид попапа соответствует скриншоту [active-layout]
      - do: кликнуть на попап
      - assert: попап исчез

v-team: goods

files:
    - src/pages/ProductPage/tests/ProductPage.touch.hermione.ts
