feature: Ecom-tap

params:
    exp_flags:
        - turbo-app-any-ua=1
        - analytics-disabled=1

specs:
    beforeEach:
        - do: при дальнейшей проверке указанных ожидаемых результатов обращайте внимание на любые некорректные на ваш взгляд поведения, основываясь на свой опыт использования web-приложений (например, сохранение позиции при переходах туда-обратно кнопками на устройстве, пустые экраны при переходах, кривая верстка, скачкИ элементов, плавность скролла, неработающая функциональность и т.п.)

    Внешний вид страницы листинга:
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
      - screenshot: внешний вид соответствует скриншоту [page]

    Сохраняет фильтры при шаге назад:
      - tags:
        - filters
      - do: открыть страницу https://yandex.ru/turbo/super01.ru/n/yandexturbocatalog/?category_id=13292
      - screenshot: на странице есть фасеты (категории), три из них открыты, остальные скрыты за кнопкой [category-list-initial]
      - do: раскрыть фасеты кликом по кнопке "Еще 2 раздела"
      - screenshot: фасеты раскрылись [category-list-opened]
      - do: перейти на любой товар и вернуться браузерной кнопкой 'назад'
      - assert: фасеты все еще открыты

    Сохраняет фильтры при перезагрузке:
      - tags:
        - filters
      - do: открыть страницу https://yandex.ru/turbo/super01.ru/n/yandexturbocatalog/?category_id=13292
      - screenshot: на странице есть фасеты (категории), три из них открыты, остальные скрыты за кнопкой [category-list-initial]
      - do: раскрыть фасеты кликом по кнопке "Еще 2 раздела"
      - screenshot: фасеты раскрылись [category-list-opened]
      - do: перезагрузить страницу
      - assert: фасеты все еще открыты

    Показывается заглушка при отсутствии фотографий товара:
      - do: открыть страницу https://yandex.ru/turbo/19.digitalserv.ru/n/yandexturbocatalog/?category_id=3320
      - screenshot: картинка в карточке товара заменена на заглушку [product-item]

    Переход в категорию с серпа:
        Загружается вторая страница листинга:
            - automation: TURBOUI-3909
            - do: получить выдачу по запросу "site:super01.ru каталог"
            - assert: в результатах выдачи есть турбо-сниппет с галереей карточек товаров
            - do: кликнуть по тайтлу сниппера
            - assert: открылась страница каталога
            - do: проскроллить вниз до второй страницы
            - assert: подгузились пустые карточки в которых затем загрузились картинки и страница скроллится дальше

    Открывается карточка товара с результатов поиска:
        - automation: TURBOUI-3909
        - do: получить выдачу по запросу 'site:super01.ru каталог'
        - assert: на выдаче присутствует турбо-сниппет(ы) с серой иконкой ракеты справа от гринурла
        - do: кликнуть по любой ссылке турбо-сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - assert: цветовое оформление может отличаться в зависимости от магазина [https://jing.yandex-team.ru/files/skurhanski/chrome_Gw9upIcJ8I.png]
        - do: кликнуть по пиктограмме Главная на нижней панели
        - do: в поле поиска вбить "для волос"
        - do: нажать "найти"
        - assert: открылся список товаров
        - do: нажать на любой товар
        - assert: открылась карточка товара [https://jing.yandex-team.ru/files/skurhanski/chrome_EEwdVnpIAl.png]

    Переход из навигационной панели:
        - automation: TURBOUI-3909
        - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог, 'site:super01.ru')
        - assert: на выдаче присутствует турбо-сниппет(ы) с серой иконкой ракеты справа от гринурла
        - do: кликнуть по любой ссылке турбо-сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - assert: цветовое оформление может отличаться в зависимости от магазина [https://jing.yandex-team.ru/files/skurhanski/chrome_Gw9upIcJ8I.png]
        - do: кликнуть по пиктограмме Главная на нижней панели
        - do: нажать на кнопку "Каталог" в нижней навигационной панели
        - assert: открылась страница товаров
        - assert: переход произошел без анимации

    Сортировка:
        Сначала дешевле:
            - automation: TURBOUI-3909
            - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог, 'site:super01.ru')
            - assert: на выдаче присутствует турбо-сниппет(ы) с серой иконкой ракеты справа от гринурла
            - do: кликнуть по любой ссылке турбо-сниппета для перехода на страницу магазина
            - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
            - assert: цветовое оформление может отличаться в зависимости от магазина [https://jing.yandex-team.ru/files/skurhanski/chrome_Gw9upIcJ8I.png]
            - do: кликнуть по пиктограмме Каталог на нижней панели
            - do: нажать на кнопку "По популярности"
            - do: выбрать "Сначала дешевле"
            - assert: список товаров отсортирован по возрастанию цены
            - do: проскроллить до второй страницы
            - assert: на второй странице отображаются товары по возрастанию цены

        Сначала дороже:
            - automation: TURBOUI-3909
            - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог, 'site:super01.ru')
            - assert: на выдаче присутствует турбо-сниппет(ы) с серой иконкой ракеты справа от гринурла
            - do: кликнуть по любой ссылке турбо-сниппета для перехода на страницу магазина
            - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
            - assert: цветовое оформление может отличаться в зависимости от магазина [https://jing.yandex-team.ru/files/skurhanski/chrome_Gw9upIcJ8I.png]
            - do: кликнуть по пиктограмме Каталог на нижней панели
            - do: нажать на кнопку "По популярности"
            - do: выбрать "Сначала дороже"
            - assert: список товаров отсортирован по убыванию цены
            - do: проскроллить до второй страницы
            - assert: на второй странице отображаются товары по убыванию цены

        По скидке:
            - automation: TURBOUI-3909
            - do: получить выдачу по запросу 'site:super01.ru каталог'
            - assert: на выдаче присутствует турбо-сниппет(ы) с серой иконкой ракеты справа от гринурла
            - do: кликнуть по любой ссылке турбо-сниппета для перехода на страницу магазина
            - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
            - assert: цветовое оформление может отличаться в зависимости от магазина [https://jing.yandex-team.ru/files/skurhanski/chrome_Gw9upIcJ8I.png]
            - do: кликнуть по пиктограмме Каталог на нижней панели
            - do: нажать на кнопку "По популярности"
            - do: выбрать "По скидке"
            - assert: первыми отображаются товары с наибольшей скидкой

    Отображается соответствующий текст если ничего не найдено:
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/?query=%D0%BA%D0%BA%D0%BA
        - assert: на странице есть текст "С выбранными фильтрами ничего не найдено"
        - screenshot: внешний вид соответствует скриншоту [plain]

    Опечаточник:
        Появляется при вводе запроса с опечатками:
            - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
            - do: ввести в поисковую строку запрос "поисковой запрос в котором есть опичатка"
            - assert: на странице появился опечаточник
            - screenshot: внешний вид соответствует скриншоту [plain]

        Заменяет текст в поисковой строке на исправленный:
            - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/?query=фареоп
            - assert: |
                на странице есть опечаточник
                текст в поисковой строке - "фаркоп"

        Кнопка отменить работает корректно:
            - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/?query=фареоп
            - assert: на странице есть опечаточник
            - do: в опечаточнике нажать на "Отменить"
            - assert: |
                опечаточника нет на странице
                текст в поисковой строке - "фареоп"

    Скелеты товаров:
        Внешний вид:
            - tags: no_assessors
            - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
            - do: дождаться загрузки страницы
            - do: пролистать список товаров до самого низа
            - assert: появилось не больше 4х скелетов для карточки товаров
            - screenshot: внешний вид соответствует скриншоту [skeleton]

        Должно быть не больше 4х на странице:
            - do: открыть страницу https://yandex.ru/turbo/super01.ru/n/yandexturbocatalog/?category_id=5871
            - do: дождаться загрузки страницы
            - do: пролистать список товаров до самого низа
            - assert: появилось не больше 4х скелетов для карточки товаров

        Не должно быть на странице если все товары загруженны:
            - do: открыть страницу https://yandex.ru/turbo/super01.ru/n/yandexturbocatalog/?category_id=5871
            - do: дождаться загрузки страницы
            - do: перейти в категорию "Настольные Игры"
            - do: дождаться загрузки страницы
            - do: пролистать список товаров до самого низа
            - assert: скелеты  для карточек товаров не появляются

    Анимациия перелистывания:
        - automation: TURBOUI-4170
        - do: получить выдачу по запросу 'site:super01.ru' (альтернативные запросы - 'site:kupicase.ru каталог')
        - assert: на выдаче присутствует турбо-сниппет(ы) с серой иконкой ракеты справа от гринурла
        - do: кликнуть по любой ссылке турбо-сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - do: кликнуть по пиктограмме Каталог на нижней панели
        - assert: в разделе есть список категорий  [https://jing.yandex-team.ru/files/skurhanski/chrome_uUHDsEeLUJ.png]
        - do: кликнуть по любой категории и далее кликать по подкатегориям, пока не окажетесь в раздере без подкатегорий
        - assert: при переходах срабатывает анимация

    Показывает попап при добавлении с листинга:
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
        - do: нажать "в корзину у трех товаров"
        - screenshot: все три раза показался, а затем прятался попап [bottom-bar-popup]
        - do: добавить товар в четвертый раз
        - assert: попап не показался

    Пробрасывать параметр для рекомендаций в следующие страницы:
      - tags: no_assessors
      - params:
          turbo_listing_ecom_recom_offer_num: '20'
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
      - assert: на странице есть листинг
      - do: проскроллить страницу до конца
      - assert: загрузились еще карточки товаров
      - do: открыть network и найти запрос за страницей с параметром `page=1`
      - assert: в урле на дозагрузку есть параметр `turbo_listing_session_id=some_id_0`
      - do: проскроллить страницу до конца
      - assert: загрузились еще карточки товаров
      - do: открыть network и найти запрос за страницей с параметром `page=2`
      - assert: в урле на дозагрузку есть параметр `turbo_listing_session_id=some_id_0`

    Избранное в листинге:
      - params:
          exp_flags:
            - turboforms_endpoint=/multiple/
      - do: залогиниться на yandex.ru
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/?category_id=9
      - assert: |
          открылась страница каталога
          у каждого товара отображается кнопка добавления в избранное
      - screenshot: товар с кнопкой выглядит корректно [plain]
      - do: нажать на кнопку добавления в избранное
      - screenshot: кнопка меняет цвет на красный [saved]
      - do: перезагрузить страницу
      - assert: кнопка все ещё выделена красным
      - do: повторно нажать на кнопку добавления в избранное
      - screenshot: кнопка больше не выделена красным [deleted]

    Сворачиваются категории если их больше 30:
      - do: открыть страницу https://yandex.ru/turbo/moskva.satom.ru/n/yandexturbocatalog/
      - assert: |
          открылась страница каталога
          отображается 3 категории
          есть кнопка для показа остальных категорий

    Скрытие кол-ва товаров в категориях в листинге:
      - params:
          exp_flags:
            - turbo-app-hide-category-count=1
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
      - screenshot: список категорий не содержит кол-во товаров [categories]

    Рейтинг товара:
      - tags: no_assessors
      - browsers:
          notFor:
            - ios-safari-9-touch
            - ios-safari-10-touch
            - ios-safari-11-touch
      - params:
          patch: setProductReviews
          productReviews: 100,4.5
          exp_flags:
            - turbo-app-listing-reviews=1
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
      - screenshot: товар содержит рейтинг [product-item]
      - do: нажать на товар
      - tech: отправилась цель 'open-product-item' с параметрами rating=4.5, review_count=100, pos=thumb

    Рейтинг товара и кол-во отзывов в описании:
      - browsers:
          notFor:
            - ios-safari-9-touch
            - ios-safari-10-touch
            - ios-safari-11-touch
      - params:
          patch: setProductReviews
          productReviews: 100,4.5
          exp_flags:
            - turbo-app-product-list-reviews=1
            - turbo-app-listing-reviews=1
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
      - screenshot: товар содержит рейтинг и кол-во отзывов [product-item]
      - do: нажать на товар
      - tech: отправилась цель 'open-product-item' с параметрами rating=4.5, review_count=100, pos=info
      - tags: no_assessors #используются патчи

    Блоки главной на странице пустого поиска:
      - params:
          exp_flags:
            - turbo-app-global-search=1
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
      - do: Ввести в поиске 'empty123456'
      - do: нажать на кнопку "найти"
      - assert: отобразилась страница с пустим результатом
      - assert: под пустым результатом появились 3 блока с товарами "Популярные товары", "Выгодно сегодня", "Все товары"

    Рекомендательные карточки в выдаче:
      - params:
          patch:
            - setListRecommendationCard
            - setReqid
      - tags: no_assessors # используются патчи
      - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/
      - tech: отправилась цель 'product-list-seen' с параметрами host='spideradio.github.io', originalUrl='http://spideradio.github.io', place='listingPage', reqid='test-reqid'
      - do: проскроллить до первого товара, чтобы его карточка была видна как минимум на 50% (в патче он единственный)
      - tech: отправилась цель 'product-item-seen' с параметрами host='spideradio.github.io', originalUrl='http://spideradio.github.io', place='listingPage', reqid='test-reqid', productUrl='https://yandex.ru/turbo/spideradio.github.io/s/rnd/c7hj4fr?utm_source=turbo_turbo', offerId='107'
      - do: кликнуть по кнопке "В корзину"
      - tech: отправилась цель 'product-item-click-add-to-cart' с параметрами host='spideradio.github.io', originalUrl='http://spideradio.github.io', place='listingPage', reqid='test-reqid', productUrl='https://yandex.ru/turbo/spideradio.github.io/s/rnd/c7hj4fr?utm_source=turbo_turbo', offerId='107'
      - do: кликнуть по карточке товара
      - tech: отправилась цель 'product-item-click' с параметрами host='spideradio.github.io', originalUrl='http://spideradio.github.io', place='listingPage', reqid='test-reqid', productUrl='https://yandex.ru/turbo/spideradio.github.io/s/rnd/c7hj4fr?utm_source=turbo_turbo', offerId='107'

files:
- screens/ProductListScreen/__tests__/ProductListScreen@phone.hermione.js

tags:
  - ecom-tap

tlds: ru

v-team: Turbo
