feature: products-list-separator

browsers:
  - ios-safari-12-touch
  - ios-safari-11-touch
  - ios-safari-10-touch
  - ios-safari-9-touch

specs:
  Подскроливание к указанной странице:
    - tags: no_assessors
    - do: открыть ссылку https://yandex.ru/turbo?text=logomebel.ru%2Fyandexturbocatalog%2F&page=2
    - assert: страница браузера проскролена до 1 товара 2 страницы
    - screenshot: позиция товара соответствует позиции "LogoMebel Стул Eames DAW LMZL-620 светлые ножки" на скриншоте [autoscroll]

  Не должен подскроливать к нулевой странице:
    - tags: no_assessors
    - do: открыть ссылку https://yandex.ru/turbo?text=logomebel.ru%2Fyandexturbocatalog%2F&page=0
    - assert: скрол страницы на самом верху, никакого подскрола не выполнилось

  Изменение номера страницы по мере скрола вверх:
    - do: открыть ссылку https://yandex.ru/turbo?text=logomebel.ru%2Fyandexturbocatalog%2F&page=2
    - do: проскролить страницу на 3 ряда товаров вверх
    - assert: в адресной строке браузера должен установиться параметр &page=1

  Изменение номера страницы по мере скрола вниз:
    - do: открыть ссылку https://yandex.ru/turbo?text=logomebel.ru%2Fyandexturbocatalog%2F&page=2
    - do: проскролить до конца вниз и дождаться загрузки следующих товаров
    - do: проскролить до 4 товара загрузившейся страницы, чтобы он оказался в верхней половине экрана
    - assert: в адресной строке браузера должен установиться параметр &page=3

files:
  - platform/components/ProductsListSeparator/__tests__/ProductsListSeparator@phone.hermione.js

v-team: Turbo

manager: tanzwuta

tags: 
  - e-commerce
  - no_assessors #раскатили новый дизайн на 100%

qa-engineer: olga0321, dakhetov

tlds: none
