feature:  Сценарии

tags: 
    - release_Webview
    - iot_scenario
    - platform_common

specs:
    beforeEach:
        - do: на аккаунте есть устройства УД и устройства с датчиками

    Ограничение на количество действий в сценарии:
      - automation: QUASARUI-3056
      - tags: 
          - https://testpalm.yandex-team.ru/alice/testcases/2918
          - release_Smarthome
          - webview_regress
          - iot_timetable
      - do: Нажать `+` -> Сценарий, выбрать любое название
      - do: Тапнуть на `Добавить условие` -> Фраза -> добавить и сохранить любую фразу
      - do: Повторить добавление фразы ещё три раза (суммарно -- 4 фразы)
      - assert: Фразы сохраняются
      - do: Тапнуть на `Добавить условие`
      - screenshot: Добавление фразы отображается задизейбленным [scenarios-triggers-1]
      - assert: <img src=https://jing.yandex-team.ru/files/osennikovak/uhura_2022-06-17T15%3A57%3A00.142804.jpg alt=Скриншот>
      - do: Нажать на `Добавить условие` -> `Время` и сохранить любое точное время
      - do: Тапнуть на `Добавить условие`
      - screenshot: Добавление времени отображается задизейбленным [scenarios-triggers-2]
      - do: Нажать на `Добавить условие` -> `Устройство` и сохранить любое условие по датчику
      - screenshot: Кнопка `Добавить условие` пропала [scenarios-triggers-3]
      - do: Нажать на любую фразу
      - screenshot: Появляется шторка с кнопками `Редактировать` и `Удалить` [scenarios-triggers-4]
      - do: Нажать `Удалить`
      - assert: Шторка закрылась
      - assert: Кнопка `Добавить условие` появилась
      - do: Тапнуть на `Добавить условие`
      - screenshot: Добавление таймера и условия по устройству отображается задизейбленным [scenarios-triggers-5]

