feature: Спец.размещение

specs:
  Внешний вид:
    Отель:
      - params:
          foreverdata: '773523505'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: появился рекламный сниппет с отелем
      - screenshot: пример внешнего вида рекламного сниппета [hotel]
    Приложение без картинки бесплатно:
      - params:
          foreverdata: '192962816'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: ппоявился рекламный сниппет приложения без картинки, бесплатно
      - screenshot: пример внешнего вида рекламного сниппета приложения без картинки, бесплатно [free-app-no-img]
    Приложение без картинки c ценой:
      - params:
          foreverdata: '1218934458'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: появился рекламный сниппет приложения без картинки, c ценой
      - screenshot: пример внешнего вида рекламного сниппета приложения без картинки, c ценой [paid-app-no-img]
    Приложение full:
      - params:
          foreverdata: '3943150659'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: появился рекламный сниппет приложения
      - screenshot: пример внешнего вида рекламного сниппета приложения [full-app-view]
    БНО только с возрастной меткой:
      - tags: [BNO, disclaimer, smoke]
      - params:
          foreverdata: '1731663683'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: появился рекламный сниппет БНО только с возрастной меткой
      - screenshot: пример внешнего вида рекламного сниппета БНО только с возрастной меткой [bno-only-age-warning]
    Локализация:
      - params:
          lr: '11508'
          l10n: 'tr'
          tld: 'com.tr'
      - do: получить выдачу по запросу 'banka kredi' в yandex.com.tr и поставить город Istanbul в месторасположении (проскроллить выдачу, если в начале выдачи нет рекламного сниппета)
      - screenshot: внешний вид [premium_tr]
      - assert: на выдаче присутствует рекламный сниппет с лейблом турецком языке
    Мета:
      - tags: 
         - smoke
      - params:
          foreverdata: '3203126362'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: появился рекламный сниппет c метой
      - screenshot: пример внешнего вида рекламного сниппета с метой [premium_meta]

files:
  - features/desktop/serp-adv-item/serp-adv-item.hermione.js

tags:
  - skip_e2e_check
  - adv

v-team: Distribution

tlds: all
