feature: Футер

specs:
  aliases:
    - &CheckMetrics
      - assertMetrics:
          - web.abandonment
          - web.full_abandonment
          - web.total_all_click
          - web.total_click_count
          - web.total_title_click
          - web.total_navurl_click
          - web.total_request_count
          - web.tech_part_misc_click
    - &CheckCompetitorsForForeignTlds
      - assert: |
          в футере присутствует блок 'поиск в других системах'
          в блоке отображаются две ссылки
          порядок ссылок Google, Bing
    - &OpenSerpFooter
      - do: получить выдачу по запросу 'test'
      - do: проскроллить страницу до низа страницы
      - assert: на странице присутствует блок с ссылками на регион, ссылки на другие поисковики и другие

  Стандартные проверки:
    Внешний вид:
      - tags: pp_new_core
      - *OpenSerpFooter
      - screenshot: внешний вид [footer]

    Переключатель региона:
      Внешний вид:
        - *OpenSerpFooter
        - assert: в футере присутствует блок геолокации
        - screenshot: внешний вид [region-change]
      Отправка счетчиков:
        - tags: counters
        - browsers:
            notFor:
              - searchapp-phone-group
        - *OpenSerpFooter
        - do: нажать на блок локации
        - assert: в текущей вкладке происходит переход на yandex.ru/tune/geo
        - tech: сработал счётчик path='/$page/$footer/region'

    Поиск в других системах:
      Внешний вид:
        - tlds: ru
        - *OpenSerpFooter
        - assert: в футере присутствует блок поиска в других системах
        - screenshot: внешний вид [searchengines]
      Отправка счетчиков:
        - tlds: ru
        - tags: counters
        - *OpenSerpFooter
        - assert: в футере присутствует блок поиска в других системах
        - do: кликнуть по ссылке на Google
        - assert: в новой вкладке происходит переход на поиск google
        - tech: по нажатию на ссылку срабатывает счетчик path=/$page/$footer/link[@type="google"]
        - *CheckMetrics
        - do: кликнуть по ссылке на Bing
        - assert: в новой вкладке происходит переход на поиск bing
        - tech: по нажатию на ссылку срабатывает счетчик path=/$page/$footer/link[@type="bing"]
        - *CheckMetrics
        - do: кликнуть по ссылке на Mail
        - assert: в новой вкладке происходит переход на поиск mail
        - tech: по нажатию на ссылку срабатывает счетчик path=/$page/$footer/link[@type="mail"]
        - *CheckMetrics
      Блок поиска в других системах для домена .com.tr:
        - tlds: com.tr
        - *OpenSerpFooter
        - do: получить выдачу по любому запросу в домене yandex.com.tr
        - assert: внизу страницы в футере отсутствует блок 'Поиск в других системах'
      Блок поиска в других системах для .by:
        - tlds: by
        - params:
            l10n: be
        - *OpenSerpFooter
        - *CheckCompetitorsForForeignTlds
      Блок поиска в других системах для .kz:
        - tlds: kz
        - params:
            l10n: kk
        - *OpenSerpFooter
        - *CheckCompetitorsForForeignTlds
      Блок поиска в других системах для .ua:
        - tlds: ua
        - params:
            l10n: uk
        - *OpenSerpFooter
        - *CheckCompetitorsForForeignTlds
      Блок поиска в других системах для .com:
        - tlds: com
        - params:
            lr: '87'
        - *OpenSerpFooter
        - *CheckCompetitorsForForeignTlds

    Обратная связь и справка:
      Внешний вид:
        - *OpenSerpFooter
        - assert: в футере присутствует блок 'Обратная связь и справка'
        - screenshot: внешний вид [feedback]
      Отправка счетчиков для ссылки 'Обратная связь':
        - tags: counters
        - *OpenSerpFooter
        - do: нажать на ссылку 'Обратная связь'
        - assert: в отдельной вкладке происходит переход на feedback.yandex.ru
        - tech: сработал счётчик path='/$page/$footer/feedback'
      Отправка счетчиков для ссылки 'Справка':
        - tags: counters
        - *OpenSerpFooter
        - do: нажать на ссылку 'Справка'
        - assert: в отдельной вкладке происходит переход на yandex.ru/support/search
        - tech: сработал счётчик path='/$page/$footer/help'

    Настройки:
      Внешний вид:
        - browsers:
            notFor:
              - searchapp-phone-group
        - *OpenSerpFooter
        - assert: в футере присутствует блок 'Настройки'
        - screenshot: внешний вид [settings]
      Отправка счетчиков для ссылки 'Настройки':
        - tags: counters
        - browsers:
            notFor:
              - searchapp-phone-group
        - *OpenSerpFooter
        - do: нажать на ссылку 'Настройки'
        - assert: в текущей вкладке происходит переход на yandex.ru/tune/search
        - tech: сработал счётчик path='/$page/$footer/settings'

  Пустой поисковый запрос:
    - browsers:
        notFor:
          - searchapp-phone-group
    - tlds: all
    - tags:
        - smoke_extended
    - do: получить выдачу с пустым поисковым запросом (получить пустой поисковый запрос на десктопе можно убрав в урле значение у параметра '&text=')
    - do: проверить состав ссылок в футере
    - screenshot: внешний вид соответствует скриншоту (для тачей с небольшим разрешением экрана нужно проскроллить выдачу вниз) [plain]

  С флагом pumpkin:
    - params:
        exp_flags: pumpkin=1
    - do: получить выдачу по запросу 'pumpkin'
    - do: проскролить до низа страницы
    - assert: внизу страницы присутствует футер
    - screenshot: внешний вид [footer-pumpkin]

files:
  - src/features/SerpFooter/SerpFooter.test/SerpFooter@common.hermione.js

v-team: Beauty

tlds: all

tags:
  - react
  - footer
