feature: Настройки - режим поиска

files:
  - tests/hermione/suites/touch/legacy/settings-content-access/settings-content-access.hermione.js

specs:
  'Страница открывается':
    - automation: TODO
  'Перещелкивается таб детскости':
    - automation: TODO
