feature: Настройки Яндекс.Новостей на десктопе

specs:
  позволяют добавить и удалить источник в Мои источники [manual]:
    - tags:
      - backend_news
      - smoke_zen
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: нажать на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210413_183225.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: нажать на поле поиска 'Найти источник'
    - assert: происходит переход на страницу поиска для ввода названия источника https://jing.yandex-team.ru/files/an-smirn0v/shot_210413_183622.png
    - do: ввести название 'РБК'
    - assert: появляется список с похожими названиями источников
    - do: нажать по звездочке возле источника 'РБК' (если звездочка уже прокрашена, выбрать другое название)
    - assert: отобржается всплывающая подсказка 'Добавлено в избранное', источник 'РБК' добавлен в список Мои источники, звездочка прокрашена желтым
    - do: закрыть модальное окно нажав на крестик или на область за пределами попапа (черная область) и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источником 'РБК' в блоке Подробнее о событии
    - assert: точки возле источников 'РБК' прокрашены желтым
    - do: вернуться в 'Настройка источников' через аватарку пользователя и нажать на звездочку возле источника 'РБК'
    - assert: звездочка стала серой
    - do: закрыть модальное окно нажав на крестик или на область за пределами попапа (черная область) и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источником 'РБК' в блоке Подробнее о событии
    - assert: точки возле источников 'РБК' и в заголовке отсуствуют

  позволяют авторизованному пользователю добавить источник в избранное и удалить его из меню сюжета [manual]:
    - tags:
      - smoke
      - backend_news
    - do: авторизоваться на сервисе
    - do: перейти в любой сюжет
    - do: доскроллить до блока 'Подробнее о событии' и ниже самого блока кликнуть на кнопку 'Троеточие' (внешний вид кнопки - https://jing.yandex-team.ru/files/kossakovskaya/2021-09-22_16-46-48.png)
    - do: выбрать 'Настроить источники'
    - assert: отбражается список источников, напротив каждого источника есть иконка звездочки
    - do: тапнуть по серой звездочке возле источника, который был в хвосте (блок "Подробнее о событии")
    - assert: звездочка поменяла цвет на желтый c анимацией
    - do: закрыть окно настроек и обновить страницу сюжета
    - assert: |
        источник с желтым кружочком переместился в верх списка,
        если в сюжете уже были избранные источники - они все вверху списка источников
    - do: нажать на кнопку 'Троеточие' и выбрать в списке 'Настроить источники'
    - do: в списке найти источник, который был добавлен в избранное на шаге 5 и нажать на желтую звездочку напротив источника
    - assert: звездочка снова отображается серым контуром
    - do: закрыть модальное окно и обновить страницу
    - assert: источник располагается на любом месте
    - do: разлогиниться и обновить страницу сюжета
    - assert: возле источников отсуствуют точки избранного

  выделяются для авторизованного пользователя иконкой-индикатором над заголовком в сюжете и в рубрике [manual]:
    - tags:
        - smoke
        - backend_news
        - NOTruntime
    - do: авторизоваться на сервисе
    - do: кликнуть на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        открылось модальное окно настроек,
        отображаются описание, поле поиска 'Найти источник', список источников,
        напротив источников имеются кнопки добавления в избранные, и в нежелательные,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210413_183225.png (набор источников может отличаться)
    - do: если есть добавленные источники - тапнуть на каждую желтую звездочку
    - assert: отображается всплывающие сообщение 'Удалено из избранного', звездочки больше не желтые
    - do: нажать на поле поиска 'Найти источник'
    - assert: появилась строка инпута для ввода названия источника https://jing.yandex-team.ru/files/an-smirn0v/shot_210413_183622.png
    - do: ввести название 'Lenta.ru'
    - assert: появляется садджест с похожими названиями источников
    - do: кликнуть по звездочке возле источника 'Lenta.ru'
    - assert: отображается всплывающие сообщение 'Добавлено в избранное', звездочка прокрашена желтым
    - do: нажать на кнопку стрелочки (назад) в поле поиска 'Найти источник'
    - assert: отображается модальное окно настроек, источник 'Lenta.ru' отображается в списке избранных источников, звездочка прокрашена желтым
    - do: закрыть окно настроек и перейти в любую рубрику, например, в Общество
    - do: скроллить ленту рубрики
    - assert: |
        в ленте рубрики есть карточки от источника 'Lenta.ru' (весь топ-5 может быть от этого источника),
        в каждой карточке от источника 'Lenta.ru' отображается желтая точка у иконки источника,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210413_184205.png
    - do: перейти в любой сюжет от источника 'Lenta.ru' кликом по заголовку в карточке
    - assert: |
        в сюжете над заголовком источник - 'Lenta.ru',
        возле иконки источника отображается желтая точка,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210413_184318.png
    - do: тапнуть по источнику с точкой у иконки
    - assert: в отдельной вкладке открывается статья в источнике 'Lenta.ru'

  позволяют добавить и удалить источник в Нежелательные источники [manual]:
    - tags:
      - backend_news
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: нажать на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_155049.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: нажать на поле поиска 'Найти источник'
    - assert: происходит переход на страницу поиска для ввода названия источника https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_155151.png
    - do: ввести название 'Известия'
    - assert: появляется список с похожими названиями источников
    - do: нажать на кнопку добавления в нежелательное возле источника 'Известия' (если она уже прокрашена, выбрать другое название)
    - assert: отобржается всплывающая подсказка 'Добавлено в нежелательное', источник 'Известия' добавлен в список Мои источники,
        иконка прокрашена красным,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_155303.png
    - do: закрыть модальное окно нажав на крестик или на область за пределами попапа (черная область) и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источником 'Известия' в блоке Подробнее о событии
    - assert: источники встречаются редко или не встречаются совсем
    - do: вернуться в 'Настройка источников' через аватарку пользователя
    - do: нажать на кнопку удаления из нежелательного возле источника 'Известия'
    - assert: кнопка возле источника изменилась на серую
    - do: обновить страницу
    - assert: автоматически раскрывается модальное окно настроек источников
    - do: в поле поиска ввести название 'Известия'
    - assert: в источнике 'Известия' иконка добавления в нежелательное покрашена в серый цвет

  позволяют добавить издательство в избранные источники [manual]:
    - tags:
        - backend_news
        - smoke_zen
    - do: зайти на сервис без авторизации
    - do: перейти по ссылке https://yandex.ru/news?favid=1048
    - assert: |
        открылось модальное окно с предложением авторизации для добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/kossakovskaya/2021-07-03_18-02-38.png
    - do: нажать на кнопку Войти и авторизоваться на сервисе
    - assert: |
        после авторизации автоматически открывается модальное окно с предложением добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/kossakovskaya/2021-07-03_18-03-06.png
    - do: кликнуть по кнопке Добавить источник
    - assert:
        появилась надпись - '«Коммерсантъ» в избранном'
        отображаются кнопки "Готово" и "Настроить другие источники"
    - do: кликнуть на кнопку "Готово"
    - do: кликнуть на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        открывается модальное окно настроек,
        источник из окна на шаге 1 добавлен в список Мои источники,
        звездочка возле источника прокрашена желтым
    - do: закрыть модальное окно, кликнув по крестику
    - do: поискать сюжеты с этим источником в блоке Подробнее о событии
    - assert: возле источника из окна на шаге 1 отображаются желтые кружочки

  позволяют открыть окно настройки избранных источников [manual]:
    - tags:
        - backend_news
    - do: зайти на сервис без авторизации
    - do: перейти по ссылке https://yandex.ru/news?favid=1048
    - assert: |
        раскрылось модальное окно с предложением авторизации для добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/kossakovskaya/2021-09-08_14-23-06.png
    - do: нажать на кнопку Войти и авторизоваться на сервисе
    - assert: |
        после авторизации автоматически раскрывается модальное окно с предложением добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/kossakovskaya/2021-09-08_14-21-00.png
    - do: нажать по кнопке Добавить источник
    - assert:
        появилась надпись - '«Коммерсантъ» в избранном'
        отображаются кнопки "Готово" и "Настроить другие источники"
    - do: кликнуть по кнопке "Настроить другие источники"
    - assert: открылось модальное окно настройки источников https://jing.yandex-team.ru/files/kossakovskaya/2021-04-19_17-01-26.png

  позволяют добавлять и удалять избранные источники в настройках пользователя на нацдоменах [manual]:
    - tags:
#        - ua_suite
        - by_suite
        - backend_news
        - smoke_zen
    - tlds:
 #       - ua
        - by
    - reasonNotToAuto:
      - Нет возможности автоматизировать проверку на нацдомене, т.к. команда yaGoTld не сохраняет дамп
    - automation:
      - NERPA-12077
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: перейти на страницу https://yandex.by/tune/geo и выставить город "Минск"
    - do: перейти на тестовый стенд
    - do: Перейти в любой новостной сюжет
    - do: нажать на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
    - do: добавить несколько источников в избранные
    - assert: у источников отображаются желтые звездочки
    - do: добавить несколько источников в нежелательные
    - assert: у источников отображаются красные иконки
    - do: закрыть модальное окно нажав на крестик или на область за пределами попапа (черная область) и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источниками, добавленными ранее в окне настроек, в блоке Подробнее о событии
    - assert: |
        точки возле источников из списка Мои источники прокрашены желтым,
        Нежелательные источники встречаются редко или не встречаются вовсе
    - do: вернуться в 'Настройка источников' через аватарку пользователя
    - do: добавить несколько источников из списка Нежелательные в список Мои источники
    - do: перейти в ленту сюжетов, поискать сюжеты с этими источниками
    - assert: точки возле источников прокрашены желтым

  позволяют авторизоваться с помощью избранного на нацдоменах в сюжете [manual]:
    - tags:
#      - ua_suite
      - by_suite
      - backend_news
    - tlds:
#      - ua
      - by
    - reasonNotToAuto:
      - Нет возможности автоматизировать проверку на нацдомене, т.к. команда yaGoTld не сохраняет дамп
    - automation:
      - NERPA-12077
    - do: разлогиниться на сервисе, если были залогинены
    - do: перейти на страницу https://yandex.by/tune/geo и выставить город "Минск"
    - do: перейти на тестовый стенд
    - do: перейти в любой сюжет
    - do: доскроллить до блока 'Подробнее о событии' и ниже самого блока кликнуть на кнопку 'Троеточие' (внешний вид кнопки - https://jing.yandex-team.ru/files/kossakovskaya/2021-09-22_16-46-48.png)
    - do: выбрать 'Настроить источники'
    - assert: |
        отображается кнопка 'Войти', на фоне кнопки отбражается некликабельный список источников
    - do: нажать на кнопку 'Войти'
    - assert: появился попап с предложением авторизации
    - do: авторизоваться на сервисе
    - assert: произошел возврат к сюжету, открыто окно 'Настройка источников', кнопки у источников для добавления в избранные и нежелательные становяться кликабельными

  можно открыть из меню трех точек авторизованному пользователю:
    - tags:
      - backend_news
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: нажать на меню трех точек внизу сюжета
    - assert: появляется поп-ап, содержащий пункты Настроить источники, Статистика сюжета, Автовоспроизведение видео,
    - do: нажать на пункт 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_155049.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: закрыть модальное окно нажав на крестик
    - assert: модальное окно закрывается

  можно открыть из меню трех точек неавторизованному пользователю:
    - tags:
      - backend_news
      - smoke_zen
    - do: разлогиниться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: нажать на меню трех точек под аннотацией сюжета
    - assert: |
        появляется поп-ап, содержащий пункты Настроить источники, Статистика сюжета, Автовоспроизведение видео,
        ВНИМАНИЕ! в траурном сюжете Автовоспроизведение видео отсутствует, это ок, заводить на это баг не нужно!
    - do: нажать на пункт 'Настройка источников'
    - assert: |
        открылось модальное окно "Настройка источников" с кнопкой Войти,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_161112.png
    - do: закрыть модальное окно нажав на крестик
    - assert: модальное окно закрывается

  позволяют авторизоваться через модальное окно избранного [manual]:
    - tags:
      - backend_news
    - do: разлогиниться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: нажать на меню трех точек под аннотацией сюжета
    - assert: появляется поп-ап, содержащий пункты Настроить источники, Статистика сюжета, Автовоспроизведение видео
    - do: нажать на пункт 'Настройка источников'
    - assert: |
        открылось модальное окно "Настройка источников" с кнопкой Войти,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_161112.png
    - do: авторизоваться, нажав на кнопку Войти в модальном окне
    - assert: после авторизации открывается страница сюжета с открытым модальным окном настроек

  можно открыть по кнопке из блока Подробнее о событии:
    - tags:
      - backend_news
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: нажать на кнопку настрокек в блоке 'Подробнее о событии' (внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_161906.png)
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_155049.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: закрыть модальное окно нажав на крестик
    - assert: модальное окно закрывается

  показывают тултип для неавторизованного пользователя:
    - do: открыть любой сюжет в незалогине и с удаленной кукой nc
    - assert: тултип избранного показывается возле кнопки меню сюжета
    - do: кликнуть на крестик в тултипе
    - assert: тултип исчезает

  показывают тултип возле заголовка для авторизованного пользователя:
    - do: авторизоваться и открыть любой сюжет с избранным источником в заголовке
    - do: удалить куку nc
    - assert: тултип избранного показывается возле заголовка

  показывают тултип возле заголовка в хвосте для авторизованного пользователя:
    - do: авторизоваться и открыть любой сюжет с избранным источником в хвосте
    - do: удалить куку nc
    - assert: тултип избранного показывается возле заголовка в хвосте

files:
  - features/news/settings/settings.desktop.hermione.js

qa-engineer: nightsonne

manager: mrwhite

tags:
  - neo
  - settings

tlds:
  - ru
  - by
  - kz
  - uz
  - ua
  - com
