feature: Сниппеты
type: Метка свежести

specs:
  ru:
    Внешний вид:
      - params:
          foreverdata: '2043453900'
          user_time: '202007170901'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: на выдаче есть сниппет с голубой меткой свежести
      - assert: метка свежести находится справа от гринурла
      - screenshot: примерный внешний вид [fresh-label]
    С длинным гринурлом:
      - params:
          foreverdata: '702343261'
          user_time: '202007170901'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: на выдаче есть сниппет с голубой меткой свежести
      - assert: метка свежести находится справа от гринурла
      - screenshot: примерный внешний вид [fresh-label]
  en:
    Внешний вид:
      - params:
          foreverdata: '2043453900'
          user_time: '202007170901'
          tld: 'com'
          l10n: 'en'
          lr: '10393'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: на выдаче есть сниппет с голубой меткой свежести
      - assert: метка свежести находится справа от гринурла
      - screenshot: примерный внешний вид [fresh-label]
    С длинным гринурлом:
      - params:
          foreverdata: '702343261'
          user_time: '202010011001'
          tld: 'com'
          l10n: 'en'
          lr: '10393'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: на выдаче есть сниппет с голубой меткой свежести
      - assert: метка свежести находится справа от гринурла
      - screenshot: примерный внешний вид [fresh-label]
    С длинным гринурлом и длинным текстом метки:
      - params:
          foreverdata: '702343261'
          user_time: '202010031001'
          tld: 'com'
          l10n: 'en'
          lr: '10393'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: на выдаче есть сниппет с голубой меткой свежести
      - assert: метка свежести находится справа от гринурла
      - screenshot: примерный внешний вид [fresh-label]

files:
  - features/touch-phone/special-dates/special-dates.hermione.js

v-team: Suggest_Freshness

tlds: all
