feature: Шапка

import-labels:
  - features/misspell/misspell_type_empty-request@deskpad.testpalm.yml

specs:
  aliases:
    - &CheckMetrics
      - assertMetrics:
          - web.reformulations_rate
          - web.total_rerequest_count
          - web.rerequest_per_user
          - web.part_rerequest
          - web.total_all_click
          - web.total_request_count
          - web.total_click_count
          - web.tech_part_misc_click
          - web.abandonment
          - web.full_abandonment
          - web.empty_query_rate
          - web.empty_serps_rate
    - &CheckGeoMetrics
      - assertMetrics:
          - web.total_request_count
          - web.total_click_count
          - web.abandonment
          - web.full_abandonment
          - web.geo.part_request_gc_eq_lr
          - web.geo.part_request_gc_neq_lr
  Базовые проверки:
    Проверки функциональности крестика:
      - browsers:
          notFor:
            - android-yandex-browser-17-pad
            - ios-yandex-browser-17-pad
      - do: получить выдачу по запросу 'колендарь'
      - *CheckMetrics
      - assert: крестик присутствует в поисковой строке
      - tags:
          - smoke
          - smoke_extended
      - tlds: all
      - do: кликнуть в крестик в поисковой строке
      - assert: поисковая строка очистилась
      - tech: проверить счётчик в крестике поисковой строки
      - *CheckMetrics
    Исправленного текста запроса в инпуте:
      - browsers:
          notFor:
            - searchapp-pad
            - android-yandex-browser-17-pad
            - ios-yandex-browser-17-pad
      - tags:
          - smoke_extended
      - tlds: all
      - do: получить выдачу по запросу 'колендарь'
      - assert: запрос в поисковой строке исправился на 'календарь'
      - do: кликнуть инпут поисковой строки
      - assert: в поисковой строке указан исправленный запрос - календарь
    Проверка инпута с текстом:
      - tlds: all
      - do: получить выдачу по запросу 'O_O'
      - screenshot: внешний вид стрелки шапки [with-text]
    Проверка инпута с длинным текстом:
      - tlds: all
      - do: получить выдачу по запросу 'Текстовые (строковые) литералы в C++ представляются как последовательность символов, заключенная в двойные кавычки.'
      - screenshot: внешний вид стрелки шапки [with-long-text]
    Проверка шапки с различными флагами и локалями:
      Tabs_order_version=search,images,video,maps,market,news,all:
        - params:
            exp_flags: tabs_order_version=search,images,video,maps,market,news,all
        - tlds: all
        - do: получить выдачу по запросу 'test'
        - screenshot: табики расположены в таком порядке и выглядят таким образом [plain]
      Tabs_order_version=search,blogs,images,video,maps,news,market,all:
        - params:
            exp_flags: tabs_order_version=search,blogs,images,video,maps,news,market,all
        - tlds: all
        - do: получить выдачу по запросу 'test'
        - screenshot: табики расположены в таком порядке и выглядят таким образом [plain]
      Tabs_order_version=search,images,video,news,maps,market,znatoki,all:
        - params:
            exp_flags: tabs_order_version=search,images,video,news,maps,market,znatoki,all
        - tlds: all
        - do: получить выдачу по запросу 'test'
        - screenshot: табики расположены в таком порядке и выглядят таким образом [plain]
      Проверка на локали .com:
        - tags:
            - no_assessors
        - params:
            tld: com
            lr: '87'
        - do: получить выдачу по запросу 'test'
        - screenshot: табики расположены в таком порядке и выглядят таким образом [plain]
        - *CheckGeoMetrics
      Проверка на локали .com.ge:
        - tags:
            - no_assessors
        - params:
            tld: com.ge
            l10n: ru
        - do: получить выдачу по запросу 'test'
        - screenshot: табики расположены в таком порядке и выглядят таким образом [plain]
        - *CheckGeoMetrics
      Проверка на локали .com.tr:
        - tags:
            - no_assessors
        - params:
            tld: com.tr
            l10n: tr
        - do: получить выдачу по запросу 'test'
        - screenshot: табики расположены в таком порядке и выглядят таким образом [plain]
        - *CheckGeoMetrics

files:
  - features/deskpad/yandex-search/yandex-search.hermione.js

v-team: Beauty

tags:
  - reviewed

tlds: all
