feature: Поезда
type: Подтверждение
description: >-
    Перейти на вкладку ЖД билеты

    Перейти на покупку для любого поезда на любую дату по направлению Москва -
    Санкт-Петербург, выбрать одного пассажира и заполнить все поля ввода данных
    валидными значениями. Находимся на странице ввода данных.
specs:
    'ЖД - Реквизиты компаний партнеров на странице подтверждения':
        - do: Кликнуть по кнопке Проверить заказ и купить
        - assert: >-
              * Произошел переход на страницу подтверждения

              * На странице подтверждения под корзиной с расчетом стоимости есть текст
              "Данные предоставлены партнёрами."

              ![image](https://jing.yandex-team.ru/files/shenfeld/2020-06-22_12.27.37-zl1e2.png)

              * Текст расположен как на скрине
        - do: Кликнуть по ссылке "партнерами"
        - assert: >-
              * Открылось модальное окно с заголовком Реквизиты

              * На странице за пределами окна появилась тень

              * В окне перечислены реквизиты: перевозчика, партнера, страховщика,
              Яндекса

              * Для каждой из компаний есть ОГРН, адрес (если фактический и
              юридический адрес отличаются, то отображаются они оба, если совпадают,
              то просто отображается один адрес) и время работы
        - do: Кликнуть по области за пределами окна
        - assert: |-
              * Окно закрылось
              * Тень на странице исчезла

files:
    - tests/common/trains/order/confirmation/trains-confirmation-partners.hermione.ts

Функциональность: Действия на подтверждении
Устройство:
    - Десктоп
    - Тач
Страница: Подтверждение
Сервис: ЖД
Тестирование асессорами: Да
Окружение:
    - Production
    - Testing
Tag: Smoke
Автор: shenfeld
