feature: Дежурства

specs:
  Положительные:
    1. Редактирование настроек дежурства:
      - automation: ABC-10219
      - tech: залогиниться под пользователем robot-internal-003
      - do: (PREPARE) открыть сервис "autotest-change-duty-settings" (/services/autotest-change-duty-settings/)
      - do: (PREPARE) кликнуть на иконку карандашика рядом с надписью "Управляющие" 
      - screenshot: (PREPARE) карандашик рядом с надписью "Управляющие" [https://jing.yandex-team.ru/files/pixel/Screenshot%20from%202021-04-26%2013-03-35.png]
      - do: (PREPARE) в модалке "Редактирование управляющих" в поле "Добавить сотрудника" ввести свои имя и фамилию 
      - do: (PREPARE) под полем появился выпадающий список вариантов 
      - do: (PREPARE) выбрать в выпадающем списке себя 
      - assert: (PREPARE) в блоке "Управляющие" появился выбранный сотрудник 
      - do: (PREPARE) кликнуть на кнопку "Сохранить"
      - do: открыть страницу графиков дежурств для сервиса "autotest-change-duty-settings" (/services/autotestchangedutysetting/duty)
      - assert: на странице есть график дежурства с заголовком "autotest-for-changes"
      - do: кликнуть на иконку шестерёнки рядом с заголовком графика "autotest-for-changes"
      - assert: |
              произошёл переход на страницу настроек дежурства "autotest-for-changes" (/services/autotestchangedutysetting/duty/settings/[id дежурства])
              поле "Название дежурства" заполнено значением "autotest-for-changes"
              поле "Описание дежурства" заполнено значением "Дежурство для изменений автотестом"
              поле "Slug" нередактируемое, представляет собой строку со значением "autotest_1"
              в поле "Роль" выбрано значение "Консультант"
              в поле "Роль на дежурстве" выбрано значение "Дежурный"
              поле "Одновременно дежурят" заполнено цифрой "1"
              галочка в чекбоксе "Определенный порядок участников" не стоит
              в поле "Начало дежурства" указана дата в формате "ДД месяц ГГГГ"
              в поле "Время начала дежурства (МСК)" выбрано "10:00"
              в поле "Длительность" указано значение "5"
              в поле "Автоматически подтверждать смены за" указано "0"
              стоит галочка в чекбоксе "Дежурить по праздникам"
              стоит галочка в чекбоксе "Дежурить по выходным"
              стоит галочка в чекбоксе "Не учитывать другие дежурства"
              стоит галочка в чекбоксе "Показывать как отсутствие на Staff"
      - screenshot: внешний вид карточки дежурства "autotest-for-changes" [https://jing.yandex-team.ru/files/pixel/Screenshot%20from%202021-01-27%2009-53-57.png]
      - do: кликнуть на крестик рядом со значением "Консультант" в поле "Роль"
      - assert: появился выпадающий список с ролями
      - do: кликнуть на свободное место мимо выпадающего списка 
      - assert: выпадающий список скрылся, в поле "Роль" есть плейсхолдер "Например Разработчик"
      - do: кликнуть на крестик рядом со значением "Дежурный" в поле "Роль на дежурстве"
      - assert: появился выпадающий список вариантов
      - do: кликнуть на вариант "Консультант" в выпадающем списке
      - assert: выпадающий список скрылся, в поле "Роль на дежурстве" появилось значение "Консультант"
      - do: в поле "Одновременно дежурят" изменить значение на 2
      - do: поставить галочку в чекбокс "Определенный порядок участников"
      - assert: |
              появились переключатель "Дежурят"/"Не дежурят" и список дежурных, разбитый на две части - "Дежурит сейчас" и "Дежурят следующими"
              галочка в чекбоксе "Не учитывать другие дежурства" снялась, чекбокс задизейблен
      - do: кликнуть на дату в поле "Начало дежурства"
      - assert: появился календарь
      - do: кликнуть в календаре на сегодняшнюю дату
      - assert: календарь скрылся, в поле "Начало дежурства" подставлена сегодняшняя дата в формате "ДД месяц ГГГГ"
      - do: изменить значение в поле "Время начала дежурства (МСК)" на 00:00
      - do: в поле "Длительность" указать значение "1"
      - do: в поле "Автоматически подтверждать смены за" указать значение "1"
      - do: снять галочку в чекбоксе "Дежурить по праздникам"
      - do: снять галочку в чекбоксе "Дежурить по выходным"
      - do: снять галочку в чекбоксе "Показывать как отсутствие на Staff"
      - screenshot: внешний вид карточки с изменёнными настройками [https://jing.yandex-team.ru/files/pixel/Screenshot_2021-04-27%20autotest-change-duty-settings%20—%20Настройка%20графика%20дежурств%20ABC.png]
      - do: кликнуть на кнопку "Сохранить"
      - assert: открылась страница с изменённым графиком дежурств (/services/autotestchangedutysetting/duty)
      - do: (PREPARE) кликнуть на иконку шестерёнки рядом с заголовком графика "autotest-for-changes"
      - do: (PREPARE) изменить значение поля "Роль" на "Консультант"
      - do: (PREPARE) изменить значение поля "Роль на дежурстве" на "Дежурный"
      - do: (PREPARE) в поле "Одновременно дежурят" указать значение "1"
      - do: (PREPARE) снять галочку в чекбоксе "Определённый порядок участников"
      - do: (PREPARE) указать в поле "Время начала дежурства (МСК)" значение "10:00"
      - do: (PREPARE) указать в поле "Длительность" значение "5"
      - do: (PREPARE) указать в поле "Автоматически подтверждать смены за" значение "0"
      - do: (PREPARE) поставить галочку в чекбокс "Дежурить по праздникам"
      - do: (PREPARE) поставить галочку в чекбокс "Дежурить по выходным"
      - do: (PREPARE) поставить галочку в чекбокс "Показывать как отсутствие на Staff"
      - do: (PREPARE) кликнуть на кнопку "Сохранить"
      - assert: (PREPARE) произошёл переход на страницу с изменённым графиком дежурств (/services/autotestchangedutysetting/duty)

files: []

priority: critical

tags:
  - reviewed
