feature: Объектный ответ
type: Настройка подписок

specs:
  Доступность сценария: 
    - automation: SERP-99999
    - params:
        foreverdata: '589067310'
    - do: получить выдачу по запросу 'foreverdata' (сериал друзья)
    - do: найти на выдаче карточку сериала "Друзья"
    - do: найти в карточке кнопку "Смотреть" или "Купить"
    - do: нажать на эту кнопку
    - assert: открылся список онлайн-кинотеатров для этого сериала
    - do: кнопку настройки подписок и нажать на неё
    - assert: открылся список онлайн-кинотеатров для которых можно указать подписку
    - do: выбрать подписку для кинотеатра "Okko"/"Netflix"/"AMEDIATEKA"/"IVI" и сохранить изменения
    - assert: показан список онлайн-киноатеров для этого сериала
    - do: найти в списке кинотеатр "Okko"/"Netflix"/"AMEDIATEKA"/"IVI"
    - assert: рядом с указанным кинотеатром есть кнопка "Смотреть"

files: []

tags:
  - a11y_scenario
  - skip_manual_check # исследовательский сценарий для незрячего ассессора
  - manual  

v-team: Video

tlds: all
