feature: Объектный ответ
type: Выбор кинотеатра
priority: normal

description: Кейсы ТОЛЬКО для прохождения на территории РФ.

specs:
    Внешний вид шторки настроек:
        - tags: pp_new_core
        - params:
            foreverdata: '3779666438'
        - do: залогиниться пользователем с подпиской ПЛЮС (например, test-serp-assessors-plus/hL5-tYe-VGX-fzg)
        - do: получить выдачу по запросу 'foreverdata' ("сериал друзья")
        - assert: на выдаче в ОО присутствует карточка фильма/сериала
        - do: нажать на кнопку "Смотреть" в карточке ОО
        - assert: 
            открылась шторка с онлайн-кинотеатрами
            в правом верхнем углу шторки есть кнопка "Настроить" (шестерёнка)
        - do: нажать на кнопку "Настроить"
        - assert: открылась шторка настройки подписок
        - do: активировать чекбокс напротив кинотеатра "Okko" (если уже активирован, то ничего не делать)
        - screenshot: примерный внешний вид шторки (галочки в других чекбоксах также могут быть установлены; количество кинотеатров может отличаться) [settings-popup]

    Сортировка после закрытия шестерёнки [manual]:
        Пользователь без подписки SVOD:
            - params:
                foreverdata: '2740881750'    
            - automation: SERP-150717
            - do: залогиниться пользователем без подписки
            - do: получить выдачу по запросу 'foreverdata' ("сериал друзья")
            - assert: на выдаче в ОО присутствует карточка фильма/сериала
            - do: нажать на кнопку "Смотреть" (или "Купить") на заглушке в карточке ОО
            - assert: 
                открылась шторка с онлайн-кинотеатрами
                в правом верхнем углу шторки есть кнопка "Настроить" (шестерёнка)
            - do: нажать на кнопку "Настроить"
            - assert: |
                открылась шторка настройки подписок
                чек-боксы не установлены, иначе снять все чек-боксы, нажать "Сохранить" и повторить кейс сначала
            - do: выставить чекбоксы у кинотеатров "Кинопоиск", "AMEDIATEKA", "START" и нажать "Сохранить"
            - assert: |
                шторка настроек закрылась
                открыта шторка с выбором кинотеатров
                выбранные в шторке настроек кинотеатров находятся на первых позициях
                напротив выбранных кинотеатров отображается кнопка "Смотреть"
                на заглушке кнопка "Смотреть"
            - screenshot: примерный внешний вид шторки с выбором кинотеатров и заглушки после применения настроек (порядок кинотеатров может быть разный, важно чтобы те, у которых есть "Смотреть" были в самом верху) [https://jing.yandex-team.ru/files/kulagin-iv/Screenshot_255.png]

        Пользователь с подпиской SVOD:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]

        Пользователь без подписки AVOD:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]

        Пользователь с подпиской AVOD:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]

        Пользователь с недостаточной подпиской SVOD:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]

        Пользователь с подпиской Плюс + Амедиатека на контенте, который нельзя смотреть на СЕРПе:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]

        Пользователь с купленным контентом:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]                                             

    Залогин по шестерёнке:
        Внешний вид и автоматическое открытие попапа настроек:
            - tags: pp_new_core
            - do: разлогиниться
            - do: получить выдачу по запросу "маша и медведь" (альтернативные запросы "я худею", "балканский рубеж")
            - assert: на выдаче в ОО присутствует карточка фильма/сериала
            - do: нажать на кнопку "Купить" на заглушке в карточке ОО
            - assert: 
                открылась шторка с вариантами кинотеатров
                в правом верхнем углу шторки есть кнопка "Настроить" (шестерёнка)
            - do: нажать на кнопку "Настроить"
            - assert: произошёл переход на паспорт
            - do: залогиниться пользователем с подпиской ПЛЮС (например, test-serp-assessors-plus/hL5-tYe-VGX-fzg)
            - assert: после залогина открылась шторка с настройкой подписок
            - screenshot: внешний вид шторки (галочки в чекбоксах могут быть установлены; количество кинотеатров может отличаться) [https://jing.yandex-team.ru/files/kulagin-iv/Screenshot_256.png]

        retpath содержит ento и upf-settings:
            - tags: no_assessors #тест проверяет примерно то же самое что и "Внешний вид и автоматическое открытие попапа настроек", но нужен для гермионы
            - do: разлогиниться
            - do: получить выдачу по запросу "маша и медведь" (альтернативные запросы "я худею", "балканский рубеж")
            - assert: на выдаче в ОО присутствует карточка фильма/сериала
            - do: нажать на кнопку "Купить" на заглушке в карточке ОО
            - assert: 
                открылся попап с вариантами кинотеатров
                в правом верхнем углу попапа есть кнопка "Настроить"
            - do: проверить ссылку на кнопке "Настроить"
            - assert: ссылка содержит параметры ento=... и upf_settings=1

    Счётчики [manual]:
        Открытие шторки настроек:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]

        Закрытие шторки настроек:
            - automation: SERP-150717
            - tags: [empty_test, draft, no_assessors, skip_manual_check]                         

tags: [oo, cinema-choice, no_assessors] 
tlds: ru

v-team: Video
files: [features/touch-phone/z-entity-search/film-card/cinema-choice-settings.hermione.js]
