feature: Превью-объявлений

import-labels:
  - features/direct-preview/direct-preview@common.testpalm.yml

specs:
  Проверка ссылок:
    - params:
        text: '1'
        lr: '213'
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - screenshot: пример внешнего вида [direct-preview-{{PLATFORM}}-{{BROWSER_TYPE}} >> plain]
    - do: кликнуть на ссылку в заголовке
    - tech: ссылка ведёт на yabs.yandex.ru/count
    - assert: открылась страница https://yabs.yandex.ru/count/
    - do: кликнуть на ссылку в первом сайтлинке
    - tech: ссылка ведёт на yabs.yandex.ru/count
    - assert: открылась страница https://yabs.yandex.ru/count/
  Проверка фавиконки для РМП:
    - params:
        text: '1'
        lr: '213'
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-rmp-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: в рекламном сниппете фавиконка стора
  Проверка фавиконки для UC:
    - params:
        text: '1'
        lr: '213'
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: в рекламном сниппете фавиконка сайта
  postMessage получение высоты:
    - params:
        text: ''
        type: yabs_proxy
    - do: |
        получить объявление на /search/direct-preview/ с параметрами text, lr, type из params
        добавить в ссылку параметр &adv равный содержимому файла features/direct-preview/assets/serp-adv-item-dump.json (копировать все из файла, ссылка будет длинной - это норм)
    - assert: проверить, что в выдаче есть рекламный сниппет
    - tech: |
        выполнить в консоле
        `window.addEventListener('message', function(event) { window.height = event.data; });`
        `postMessage({ action: 'getHeight' }, origin);`
        `window.height` - должен вывести 125

files:
  - features/direct-preview/direct-preview@touch-phone.hermione.js

tags:
  - no_assessors
  - skip_e2e_check
  - direct_preview

browsers:
  notFor:
    - searchapp-phone

v-team: Distribution

tlds:
  - ru
