feature: Товарная галерея
experiment: Добавить ссылку на Товарную вертикаль

specs:
  Базовые проверки:
    - params:
        foreverdata: '1561051004'
        lr: '213'
        exp_flags:
          - ecom_tg_add_more_url=1
    - do: получить выдачу по запросу "foreverdata"
    - assert: первым результатом поисковой выдачи является товарная галерея
    - do: проскроллить товарную галерею до конца
    - assert: в конце галереи присутствует карточка "Показать больше товаров"
    - screenshot: пример внешнего вида [ecom_tg_more_url]

files:
  - features/ecom_tg/ecom_tg_add_more_url/ecom_tg_add_more_url@common.hermione.js

tags:
  - adv
  - tgallery
  - skip_e2e_check
  - ecom

v-team: ECOM

tlds: all
