feature: Одна организация
experiment: Скрытие блоков по формуле c бэкенда

specs:
  Популярные блоки скрыты:
    - params:
        exp_flags: GEO_1org_show_wizard_parts_by_backend_config=1
        foreverdata: '3524856510'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе нет блока с текстовыми фичами (они же признаки)
    - assert: в карточке на главном табе нет блока публикаций
    - assert: в карточке на главном табе нет блока меню
    - assert: в карточке на главном табе нет блока похожих организаций
    - assert: в карточке на главном табе нет блока с социальными сетями
  Популярные блоки показываются:
    - params:
        exp_flags: GEO_1org_show_wizard_parts_by_backend_config=1
        foreverdata: '3295149644'
        user_time: '20210123'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе есть блок с текстовыми фичами (они же признаки)
    - assert: в карточке на главном табе есть блок публикаций
    - assert: в карточке на главном табе есть блок меню
    - assert: в карточке на главном табе есть блок похожих организаций
    - assert: в карточке на главном табе есть блок с социальными сетями
  Врезка Недвижимости скрыта:
    - params:
        foreverdata: '825203618'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе нет блока с предложениями Недвижимости
  Врезка Автору скрыта:
    - params:
        foreverdata: '4011753627'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: на странице появилась карточка одной организации
    - assert: в карточке на главном табе нет блока с предложеними Автору

files:
  - features/companies/experiments/GEO_1org_show_wizard_parts_by_backend_config/GEO_1org_show_wizard_parts_by_backend_config@touch-phone.hermione.js

browsers: chrome-phone

v-team: VanillaGeo

tags:
  - skip_e2e_check

tlds: all
