feature: Опечатка и Ко
type: Подмешаны похожие запросы

specs:
  Базовое поведение:
    - browsers:
        notFor:
          - searchapp-phone-group
    - do: получить выдачу по запросу "foof chemistry"
    - assert: на выдаче присутствует опечаточник
    - assert: опечаточник содержит сообщение 'Добавлены результаты по запросу «food chemistry»'
    - assert: опечаточник содержит кнопку 'Отменить'
    - screenshot: внешний вид [more-results]
    - do: нажать на кнопку 'Отменить'
    - assert: выдача обновилась
    - tech: сработал счетчик '/wiz/web_misspell/misspell/source', vars 'misspell_count=p10,pos=top,source=wizard'
    - do: нажать "Назад" в браузере или устройстве
    - assert: выдача обновилась
    - assert: на выдаче присутствует опечаточник
    - do: кликнуть в ссылку 'food chemistry' в опечаточнике
    - assert: выдача обновилась
    - tech: сработал счетчик '/wiz/web_misspell/misspell/correct', vars 'misspell_count=p10,pos=top,source=wizard'
    - assertMetrics: '*'
  Базовое поведение ПП:
    - browsers:
        - searchapp-phone
    - do: получить выдачу по запросу "foof chemistry"
    - assert: на выдаче присутствует опечаточник
    - assert: опечаточник содержит сообщение 'Добавлены результаты по запросу «food chemistry»'
    - assert: опечаточник содержит кнопку 'Отменить'
    - screenshot: внешний вид [more-results]
    - do: нажать на кнопку 'Отменить'
    - assert: выдача обновилась
    - tech: сработал счетчик '/wiz/web_misspell/misspell/source', vars 'misspell_count=p10,pos=top,source=wizard'
    - assertMetrics: '*'
  Тест опечаточника на английском:
    - params:
        lr: '202'
        tld: com
        l10n: en
    - tlds: com
    - do: получить выдачу по запросу "foof chemistry"
    - assert: получена выдача по запросу "foof chemistry"
    - do: заменить домен в адресной строке на 'com' и добавить в URL параметры '&lr=202&noredirect=1&l10n=en' (если в урле уже есть параметр &lr, то заменить его на 202 и добавить остальные параметры)
    - assert: в URL отображается домен 'com' и параметры '&lr=202&noredirect=1&l10n=en'
    - assert: под поисковой стрелкой присутствует сообщение Including results for "food chemistry".
    - assert: рядом с сообщением есть кнопка "Cancel"
    - assertMetrics: '*'

specs-integration:
  beforeEach:
    - do: получить выдачу по запросу "foof chemistry"
    - assert: на выдаче присутствует опечаточник с сообщением "Добавлены результаты по запросу «food chemistry»"
    - assert: опечаточник содержит кнопку 'Отменить'
  Проверка ссылки с исправленным запросом:
    - do: нажать на первую ссылку с исправленным запросом food chemistry
    - assert: выдача обновлена
    - assert: на выдаче отсутствует опечаточник с сообщением "Добавлены результаты по запросу «food chemistry»."
    - assert: в url'e страницы в адресной строке присутствует параметр &msp=1 (отсутствует в ПП, это не является ошибкой)
    - tech: сработал счетчик '/wiz/web_misspell/misspell/correct', в vars присутствует 'pos=top,source=wizard'
    - counter: /$page[@isSearchApp != true]/$main/misspell/web_misspell/correct
  Нажатие на кнопку Отменить:
    - do: нажать на кнопку Отменить справа от опечаточника
    - assert: выдача обновлена
    - assert: на выдаче отсутствует опечаточник с сообщением "Добавлены результаты по запросу «food chemistry»."
    - assert: в url'e страницы в адресной строке присутствуют параметры &noreask=1 и &nomisspell=1 (отсутствуют в ПП, это не является ошибкой)
    - tech: сработал счетчик '/wiz/web_misspell/misspell/source', в vars присутствует 'pos=top,source=wizard'
    - counter: /$page[@isSearchApp != true]/$main/misspell/web_misspell/correct

files:
  - features/common/misspell/misspell_type_more-results.hermione.js
  - features/common/misspell/misspell_type_more-results.hermione.e2e.js

v-team: Freshness

tags:
  - reviewed

selector: .misspell

counter: /$page/$main/misspell/web_misspell/correct

tlds:
  - ru
  - by
  - ua
  - kz
  - uz
