feature: ProductItem

params:
    exp_flags:
      - analytics-disabled=1

specs:
    beforeEach:
        - do: при дальнейшей проверке указанных ожидаемых результатов обращайте внимание на любые некорректные на ваш взгляд поведения, основываясь на свой опыт использования web-приложений (например, сохранение позиции при переходах туда-обратно кнопками на устройстве, пустые экраны при переходах, кривая верстка, скачкИ элементов, плавность скролла, неработающая функциональность и т.п.)

    Внешний вид с товаром под заказ:
        - tags:
            # воспроизводится только в темпларе
              no_assessors
        - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/n/yandexturbocatalog/?patch=madeByOrderProducts
        - screenshot: внешний вид первого товара в списке соответствует скриншоту [plain]

    Добавление в корзину с поискового листинга:
        - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог)
        - assert: на выдаче присутствует сниппет(ы) с галереей карточек товаров [https://jing.yandex-team.ru/files/skurhanski/chrome_ziIi8LshqE.png]
        - do: кликнуть по любой ссылке сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - do: кликнуть по пиктограмме Главная на нижней панели
        - do: запомнить название любого товара с карточки
        - do: ввести любое слово из названия товара в поле "Поиск по товарам"
        - do: нажать "найти"
        - assert: открылся каталог с товарами
        - assert: при переходе не было анимации
        - assert: на карточках товаров подсвечено слово из поля поиска
        - screenshot: примерный внешний вид [content]
        - do: на любой карточке нажать на кнопку "В корзину"
        - assert: кнопка изменилась на "В корзине"
        - screenshot: примерный внешний вид [button]
        - do: нажать на кнопку "В корзине"
        - assert: произошел переход в корзину
        - assert: при переходе не было анимации
        - assert: товар отображается в корзине
        - screenshot: примерный внешний вид [cart]
        - do: нажать браузерную или аппаратную кнопку "назад"
        - assert: в той же вкладке открылась страница с которой был добавлен товар
        - assert: страница открылась в том же положении
        - assert: при переходе не было анимации
        - assert: после перехода страница не дернулась

    Добавление в корзину с главной товара со скидкой:
        - do: получить выдачу по запросу 'site:super01.ru'
        - assert: на выдаче присутствует сниппет(ы) с галереей карточек товаров [https://jing.yandex-team.ru/files/skurhanski/chrome_ziIi8LshqE.png]
        - do: кликнуть по любой ссылке сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - assert: цветовое оформление может отличаться в зависимости от магазина
        - do: кликнуть по пиктограмме Главная на нижней панели
        - do: проскроллить страницу вниз
        - assert: на странице есть блок со скидками
        - screenshot: примерный внешний вид [list]
        - do: нажать на кнопку "В корзину" по любому товару из блока
        - assert: кнопка изменила цвет и название "В корзине"
        - screenshot: примерный внешний вид [button]
        - do: нажать на кнопку "В корзине"
        - assert: в той же вкладке открылась без анимации страница с корзиной
        - assert: в "Итого" отображается цена со скидкой
        - assert: цена товара отображается со скидкой
        - screenshot: примерный внешний вид [price]
        - do: нажать браузерную или аппаратную кнопку "назад"
        - assert: в той же вкладке открылась страница с которой был добавлен товар
        - assert: страница открылась в том же положении
        - assert: после перехода страница не дернулась

    Добавление в корзину с главной популярного товара:
        - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог,  'site:super01.ru')
        - assert: на выдаче присутствует сниппет(ы) с галереей карточек товаров [https://jing.yandex-team.ru/files/skurhanski/chrome_ziIi8LshqE.png]
        - do: кликнуть по любой ссылке сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - assert: цветовое оформление может отличаться в зависимости от магазина
        - do: кликнуть по пиктограмме Главная на нижней панели
        - assert: на странице есть блок популярных товаров
        - screenshot: примерный внешний вид [list]
        - do: нажать на кнопку "В корзину" по любому товару из блока
        - assert: кнопка изменила цвет и название "В корзине"
        - screenshot: примерный внешний вид [button]
        - do: нажать на кнопку "В корзине"
        - assert: произошел переход в корзину без анимации
        - assert: выбранный товар отображается в корзине
        - screenshot: примерный внешний вид [cart]
        - do: нажать браузерную или аппаратную кнопку "назад"
        - assert: в той же вкладке открылась страница с которой был добавлен товар
        - assert: страница открылась в том же положении
        - assert: после перехода страница не дернулась

    Добавление в корзину после перехода в категорию с главной:
        - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог,  'site:super01.ru')
        - assert: на выдаче присутствует сниппет(ы) с галереей карточек товаров [https://jing.yandex-team.ru/files/skurhanski/chrome_ziIi8LshqE.png]
        - do: кликнуть по любой ссылке сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - assert: цветовое оформление может отличаться в зависимости от магазина
        - do: кликнуть по пиктограмме Главная на нижней панели
        - assert: на странице есть блок категорий
        - screenshot: примерный внешний вид [category]
        - do: нажать на любую категорию
        - do: нажать на кнопку "В корзину" по любому товару на открывшейся странице
        - assert: кнопка изменила цвет и название "В корзине"
        - screenshot: примерный внешний вид [button]
        - do: нажать на кнопку "В корзине"
        - assert: в той же вкладке открылась страница с корзиной
        - assert: переход произошел без анимации
        - assert: в корзине отображается выбранный товар
        - screenshot: примерный внешний вид [cart]
        - do: нажать браузерную или аппаратную кнопку "назад"
        - assert: в той же вкладке открылась страница с которой был добавлен товар
        - assert: страница открылась в том же положении
        - assert: после перехода страница не дернулась

    Добавление в корзину после перехода в категорию с серпа:
        - automation: TURBOUI-3847
        - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог, 'site:super01.ru')
        - assert: на выдаче присутствует сниппет(ы) с галереей карточек товаров [https://jing.yandex-team.ru/files/skurhanski/chrome_ziIi8LshqE.png]
        - do: кликнуть по любой ссылке сниппета для перехода на страницу магазина
        - assert: открылась страница магазина
        - do: кликнуть по пиктограмме Каталог на нижней панели
        - assert: осуществился переход в корень каталога
        - do: кликнуть по любой категории
        - assert: осуществился переход в выбранную категорию
        - do: нажать на кнопку "В корзину" по любому товару на открывшейся странице
        - do: нажать на кнопку "В корзине"
        - assert: в той же вкладке открылась страница с корзиной
        - assert: в корзине отображается выбранный товар
        - do: нажать браузерную или аппаратную кнопку "назад"
        - assert: в той же вкладке открылась страница с которой был добавлен товар
        - assert: страница открылась в том же положении
        - assert: после перехода страница не дернулась

    Добавление в корзину со второй страницы категории после перехода с главной:
        - automation: TURBOUI-3847
        - do: получить выдачу по запросу 'site:fulmar.ru' (альтернативные запросы - site:kupicase.ru каталог, 'site:super01.ru')
        - assert: на выдаче присутствует сниппет(ы) с галереей карточек товаров [https://jing.yandex-team.ru/files/skurhanski/chrome_ziIi8LshqE.png]
        - do: кликнуть по любой ссылке сниппета для перехода на страницу магазина
        - assert: открылась страница магазина с активной кнопкой Каталог на нижней панели
        - assert: цветовое оформление может отличаться в зависимости от магазина [https://jing.yandex-team.ru/files/skurhanski/chrome_Gw9upIcJ8I.png]
        - do: кликнуть по пиктограмме Главная на нижней панели
        - assert: на странице есть блок категорий [https://jing.yandex-team.ru/files/dakhetov/categories.png]
        - do: нажать на любую категорию с количеством товаров внутри больше 20
        - do: проскроллить список товаров до второй страницы (т.е. когда загрузится следующая партия карточек в ленту)
        - do: нажать на кнопку "В корзину" по любому товару на открывшейся странице
        - do: нажать на кнопку "В корзине"
        - assert: в той же вкладке открылась страница с корзиной
        - assert: при переходе не было анимации
        - assert: в корзине отображается выбранный товар
        - do: нажать браузерную или аппаратную кнопку "назад"
        - assert: в той же вкладке открылась страница с которой был добавлен товар
        - assert: страница открылась в том же положении
        - assert: после перехода страница не дернулась

    Добавление в корзину со второй страницы категории после перехода с серпа:
        - automation: TURBOUI-3847
        - params:
            foreverdata: '4227017412'
        - do: получить выдачу по запросу "foreverdata"
        - assert: в результатах выдачи есть турбо-сниппет с галереей карточек товаров
        - do: кликнуть в заголовок сниппета
        - do: проскроллить список товаров до второй страницы (т.е. когда загрузится следующая партия карточек в ленту)
        - do: нажать на кнопку "В корзину" по любому товару на открывшейся странице
        - do: нажать на кнопку "В корзине"
        - assert: в той же вкладке открылась страница с корзиной
        - assert: при переходе не было анимации
        - assert: в корзине отображается выбранный товар
        - do: нажать браузерную или аппаратную кнопку "назад"
        - assert: в той же вкладке открылась страница с которой был добавлен товар
        - assert: страница открылась в том же положении
        - assert: после перехода страница не дернулась

    storybook:
      Внешний вид с длинным названием товара:
        - tags: no_assessors
        - screenshot: внешний компонента с названием «Очень_очень_длинное_название_товара_не_влезающее_на_экран_и_обрезается» [long-word]
        - screenshot: внешний компонента с названием «Очень очень длинное название товара не влезающее на экран и обрезается» [long-text]

      Внешний вид в карусели:
        - tags: no_assessors
        - screenshot: внешний компонента [plain]

      Внешний вид на выдаче:
        - tags: no_assessors
        - screenshot: внешний компонента [plain]

      Внешний вид с рейтингом в тумбе:
        - tags: no_assessors
        - screenshot: внешний вид компонента соответствует скриншоту [plain]

      Внешний вид с рейтингом в описании:
        - tags: no_assessors
        - screenshot: внешний вид компонента соответствует скриншоту [plain]

files:
    - components/ProductItem/__tests__/ProductItem@phone.hermione.js

tlds:
    - ru

tags:
    - ecom-tap

v-team: Turbo
