feature: ProductReviewsLink

params:
  exp_flags:
    - analytics-disabled=1

specs:
  Без рейтинга и отзывов:
    - params:
        exp_flags:
          - turbo-app-product-reviews=1
    - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/s/rnd/w76c1jt?product_id=192
    - screenshot: картинка товара содержит рейтинг [image]
    - screenshot: на странице содержится кнопка "Оставить отзыв" [link]
    - do: нажать на кнопку "Оставить отзыв"
    - tech: отправилась цель 'leave-product-reviews-click'

  Без рейтинга и отзывов, под описанием:
    - params:
        exp_flags:
          - turbo-app-product-reviews=1
          - turbo-app-product-reviews-position-bottom=1
    - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/s/rnd/w76c1jt?product_id=192
    - assert: Блок с отзывами Находится ниже чем описание

  C рейтингом и отзывами:
    - tags: no_assessors
    - params:
        patch: setProductReviews
        productReviews: 100,4.5
        exp_flags:
          - turbo-app-product-reviews=1
    - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/s/rnd/w76c1jt?product_id=192
    - screenshot: картинка товара содержит рейтинг [image]
    - screenshot: на странице содержится блок с рейтингом товара [link]
    - do: нажать блок с рейтингом товара
    - tech: отправилась цель 'read-product-reviews-click'

  Внешний вид с рейтингом 5:
    - tags: no_assessors
    - params:
        patch: setProductReviews
        productReviews: 100,5
        exp_flags:
          - turbo-app-product-reviews=1
    - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/s/rnd/w76c1jt?product_id=192
    - screenshot: рейтинг товара выделен корректным цветом [link]

  Внешний вид с рейтингом 3.5:
    - tags: no_assessors
    - params:
        patch: setProductReviews
        productReviews: 100,3.5
        exp_flags:
          - turbo-app-product-reviews=1
    - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/s/rnd/w76c1jt?product_id=192
    - screenshot: рейтинг товара выделен корректным цветом [link]

  Внешний вид с рейтингом 2:
    - tags: no_assessors
    - params:
        patch: setProductReviews
        productReviews: 100,2
        exp_flags:
          - turbo-app-product-reviews=1
    - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/s/rnd/w76c1jt?product_id=192
    - screenshot: рейтинг товара выделен корректным цветом [link]

  Внешний вид с рейтингом 1:
    - tags: no_assessors
    - params:
        patch: setProductReviews
        productReviews: 100,1
        exp_flags:
          - turbo-app-product-reviews=1
    - do: открыть страницу https://yandex.ru/turbo/spideradio.github.io/s/rnd/w76c1jt?product_id=192
    - screenshot: рейтинг товара выделен корректным цветом [link]

files:
  - experiments/turbo-app-product-reviews/components/ProductReviewsLink/__tests__/ProductReviewsLink@phone.hermione.js

tags:
  - ecom-tap

tlds: ru

browsers:
  notFor:
    - ios-safari-9-touch
    - ios-safari-10-touch
    - ios-safari-11-touch

v-team: Turbo
