feature: product-page
type: С автоматическим добавлением в корзину (autoadd)

params:
  exp_flags:
    - turboforms_endpoint=https://test-turbo-forms.common.yandex.ru/
    - analytics-disabled=1

browsers:
  - ios-safari-12-touch
  - ios-safari-11-touch
  - ios-safari-10-touch
  - ios-safari-9-touch

specs:
  Без перехода в корзину:
    - do: открыть страницу https://yandex.ru/turbo?stub=ecomcartpage/default.json
    - assert: открылась страница корзины
    - do: удалить все товары, если они есть
    - assert: корзина пустая
    - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-2-server.json&autoadd=norelocate
    - assert: товар автоматически положился в корзину (в шапке рядом с иконкой корзины написано 1 и на карточке товара есть зеленая кнопка "Перейти в корзину")

  Не добавляем, если товар уже есть в корзине:
    - do: открыть страницу https://yandex.ru/turbo?stub=ecomcartpage/default.json
    - assert: открылась страница корзины
    - do: удалить все товары, если они есть
    - assert: корзина пустая
    - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-2-server.json
    - assert: открылась карточка товара
    - do: нажать "Добавить в корзину"
    - assert: товар добавился в корзину
    - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-2-server.json&autoadd=norelocate
    - assert: в корзине так и лежит один товар

  С переходом в корзину:
    - do: открыть страницу https://yandex.ru/turbo?stub=ecomcartpage/default.json
    - assert: открылась страница корзины
    - do: удалить все товары, если они есть
    - assert: корзина пустая
    - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-2-server.json&autoadd=tocart&utm_source=button
    - assert: |
        открылась карточка товара и сразу же произошел переход на корзину, в которой лежит 1 товар
        в урле есть параметр &utm_source=button

files:
  - platform/components/ProductPage/__tests__/ProductPageAutoadd@phone.hermione.js

v-team: Turbo

tags: 
  - e-commerce
  - no_assessors #раскатили новый дизайн на 100%

manager: tanzwuta

tlds: none
