feature: ProductItemStub

specs:
  Внешний вид:
    - do: открыть страницу https://yandex.ru/turbo?stub=productitemstub/default.json
    - screenshot: внешний вид соответствует скриншоту [default]
  Внешний вид, тип list:
    - do: открыть страницу https://yandex.ru/turbo?stub=productitemstub/list.json
    - screenshot: внешний вид соответствует скриншоту [list]
  Внешний вид, тип big-list:
    - do: открыть страницу https://yandex.ru/turbo?stub=productitemstub/big-list.json
    - screenshot: внешний вид соответствует скриншоту [big-list]

files:
  - platform/components/ProductItemStub/__tests__/ProductItemStub@phone.hermione.js

v-team: Turbo

manager: tanzwuta

qa-engineer: dakhetov, spv

tlds: none
