feature: product-item-anchor

specs:
  Подскроливание к указанному товару:
    - tags: no_assessors
    - do: открыть ссылку https://yandex.ru/turbo?text=logomebel.ru%2Fyandexturbocatalog%2F&page=4#p779
    - assert: страница браузера проскролена до товара "LogoMebel Барный стул MIRA 5001 жёлтый"
    - screenshot: позиция товара соответствует позиции "LogoMebel Барный стул MIRA 5001 жёлтый" на скриншоте [autoscroll]

  Подскроливание к указанному товару в оверлее:
    - tags: no_assessors
    - do: открыть локально ссылку https://yandex.ru/iframe?src=%3Fsrcrwr%3DSAAS%253Aman1-1464.search.yandex.net%253A17002%253A10000%26text%3Dlogomebel.ru%2Fyandexturbocatalog%2F%26page%3D4%23p7255
    - assert: страница браузера проскролена до товара "LogoMebel Стул Eames DAW LMZL-620 светлые ножки, серое сиденье"
    - screenshot: позиция товара соответствует позиции "LogoMebel Стул Eames DAW LMZL-620 светлые ножки, серое сиденье" на скриншоте [autoscroll]

  Не должен подскроливать к первым четырём товарам с первой страницы:
    - tags: no_assessors
    - do: открыть локально ссылку https://yandex.ru/iframe?src=%3Fsrcrwr%3DSAAS%253Aman1-1464.search.yandex.net%253A17002%253A10000%26text%3Dlogomebel.ru%2Fyandexturbocatalog%2F
    - do: подскролить страницу на 500 пикселей вниз
    - assert: в адресной строке браузера не появилось какое-либо значение после решётки

  Изменение номера товара по мере скрола вниз:
    - tags: no_assessors
    - do: открыть ссылку https://yandex.ru/turbo?text=logomebel.ru%2Fyandexturbocatalog%2F&page=4
    - do: проскролить, до товара "Авалон Подстолье из нерживеющей стали (хром)", чтобы он оказался в верхней половине экрана
    - assert: в конце адресной строки браузера должен установиться хэш `#p7962`

  Сохранение товара после его выбора:
    - do: открыть ссылку https://yandex.ru/turbo?text=logomebel.ru%2Fyandexturbocatalog%2F
    - do: проскролить до третьего ряда товаров и кликнуть по любому товару в ряду
    - assert: открылась страница этого товара
    - do: после загрузки страницы товара нажать браузерную кнопку "назад"
    - assert: страница браузера проскролена до того товара, страница которого была открыта
    - screenshot: позиция товара по вертикали соответствует позиции верхнего ряда на скриншоте [restore]

files:
  - platform/components/ProductItemAnchor/__tests__/ProductItemAnchor@phone.hermione.js

v-team: Turbo

tags: no_assessors

manager: tanzwuta

qa-engineer: olga0321, dakhetov

tlds: none
