feature: product-page
type: redesign

params:
  exp_flags:
    - turboforms_endpoint=https://test-turbo-forms.common.yandex.ru/
    - analytics-disabled=1

browsers:
  - ios-safari-12-touch
  - ios-safari-11-touch
  - ios-safari-10-touch
  - ios-safari-9-touch

specs:
  Новый футер:
    В отдельной карточке:
      - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-2-server-redesign.json
      - do: проскроллить до конца страницы
      - assert: внизу страницы есть большой темный футер
    В бесконечной ленте:
      - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-1-server-redesign.json
      - do: проскроллить до конца страницы
      - assert: в конце первой страницы есть блок со ссылками `Полная версия` и `Пожаловаться` и нет темного футера
      - assert: загрузилась еще одна страницы
      - do: проскроллить до конца второй страницы
      - assert: в конце второй страницы есть блок со ссылками `Полная версия` и `Пожаловаться` и нет темного футера

  Внешний вид всей страницы:
    - do: открыть страницу https://yandex.ru/turbo?stub=productpage/ecommerce-design.json
    - screenshot: внешний вид [plain]

files:
  - platform/components/ProductPage/__tests__/ProductPageRedesign@phone.hermione.js

v-team: Turbo

tags: 
  - e-commerce
  - no_assessors #раскатили новый дизайн на 100%

manager: tanzwuta

qa-engineer: ianislav

tlds: none
