feature: products-carousel

params:
  exp_flags:
    - analytics-disabled=1

browsers:
  - ios-safari-12-touch
  - ios-safari-11-touch
  - ios-safari-10-touch
  - ios-safari-9-touch

specs:
  beforeEach:
    - do: при дальнейшей проверке указанных ожидаемых результатов обращайте внимание на любые некорректные на ваш взгляд поведения, основываясь на свой опыт использования web-приложений (например, сохранение позиции при переходах туда-обратно кнопками на устройстве, пустые экраны при переходах, кривая верстка, скачкИ элементов, плавность скролла, неработающая функциональность и т.п.)

  Внешний вид:
    - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json
    - assert: на странице есть 2 галереи
    - screenshot: внешний вид [plain]
    - do: проскроллить первую галерею до конца
    - screenshot: внешний вид [scrolled]

  Скролл карусели рекоммендаций в оверлее[manual]:
    - automation: TURBOUI-3033
    - params:
        foreverdata: '587573479'
    - do: получить выдачу по запросу 'foreverdata' и кликнуть в заголовок первого сниппета (Тестовая страница для products-carousel — турбо)
    - assert: на странице есть галерея рекомендаций [https://jing.yandex-team.ru/files/skurhanski/chrome_FBbkj2nztc.png]
    - do: проскроллить галерею до конца
    - assert: галерея скроллится

  Baobab:
    beforeEach:
      - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json&exp_flags=validate_counters=1
    Дерево:
      - tags: no_assessors
      - tech: в baobab дереве есть узел по пути $page.$main.$result с массивом в children из 2 элементов products-carousel
      - tech: в каждом из элементов products-carousel есть массив children из 3 элементов product-item с id 5055, 6596, 4880
    Видимость продукта:
      - tags: no_assessors
      - tech: сработали клиентские счетчики event "tech", type "product-item-seen", path "$page.$main.$result.products-carousel.product-item" по 1 разу для каждой просмотренной (>50% видно) карточки товара (таких всего 4)
    Клик по продукту:
      - tags: no_assessors
      - do: нажать по первому товару
      - tech: сработал клиентский счетчик event "tech", type "product-item-click", path "$page.$main.$result.products-carousel.product-item.link"
    Клик по кнопке добавления в корзину:
        - tags: no_assessors
        - do: нажать по кнопке добавления в корзину второго товара
        - tech: сработал клиентский счетчик event "tech", type "product-item-click-add-to-cart", path "$page.$main.$result.products-carousel.product-item.button"

  Metrika:
    Цель на рендеринг карусели рекомендаций:
      - tags: no_assessors
      - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json
      - tech: в счётчик метрики 53911873 была отправлена цель ecom_recommendations_rendered

    Цель на видимость продуктов в каруселе рекомендаций:
      - tags: no_assessors
      - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json
      - tech: в счётчик метрики 53911873 были отправлены цели ecom_recommendations_seen_by_user для видимых товаров
      - do: проскролить карусель вправо, чтобы стали видны следующие товары
      - tech: в счётчик метрики 53911873 были отправлены цели ecom_recommendations_seen_by_user появившихся товаров

    Цель на клик по продукту в каруселе рекомендаций:
      - tags: no_assessors
      - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json
      - do: нажать по первому товару
      - tech: в счётчик метрики 53911873 была отправлена цель ecom_recommendations_clicked для первого товара

    Цель на клик по добавлению продукта в корзину в каруселе рекомендаций:
      - tags: no_assessors
      - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json
      - do: нажать по кнопке добавления в корзину у второго товара
      - tech: в счётчик метрики 53911873 была отправлена цель ecom_recommendations_add_to_cart для второго товара

  На странице паблишеров:
    Внешний вид:
      - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json
      - do: поскролить страницу вниз до галереи "Рекомендации"
      - screenshot: внешний вид [plain]

    Баобаб:
      - tags: no_assessors
      - do: открыть страницу https://yandex.ru/turbo?stub=productscarousel/default.json
      - do: поскролить страницу вниз до галереи "Рекомендации"
      - tech: при виде рекомендаций в баобаб отправился счетчик с типом "product-item-seen"
      - do: кликнуть по первому товару
      - tech: в баобаб отправился счетчик с типом "product-item-click-add-to-cart"

files:
  - platform/components/ProductsCarousel/__tests__/ProductsCarousel@phone.hermione.js

v-team: Turbo

tags:
  - e-commerce
  - no_assessors #раскатили новый дизайн на 100%

manager: tanzwuta

tlds: none
