feature: product-page

params:
  exp_flags:
    - analytics-disabled=1

browsers:
  - ios-safari-12-touch
  - ios-safari-11-touch
  - ios-safari-10-touch
  - ios-safari-9-touch

specs:
  Внешний вид с рекомендациями:
    Без описания:
      - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-1-server.json
      - assert: проскроллить до блока рекомендаций
      - screenshot: внешний вид [plain]
    С описанием:
      - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-2-server.json
      - assert: проскроллить до блока рекомендаций
      - screenshot: внешний вид [plain]

  Подскрол картинки в слайдере по параметру sliderimg в адресе страницы:
    - do: открыть страницу https://yandex.ru/turbo?text=https%3A%2F%2Fwww.logomebel.ru%2Fstulya-na-metallokarkase%2Fstul-kreslo-sonata-komfort.html&sliderimg=%2F%2Favatars.mds.yandex.net%2Fget-turbo%2F1778853%2Frth680dc13d5d42b65e47b1a86df7dc22fd%2F
    - assert: открыта третья картинка товара в слайдере

  Картинка в форме 1 клика:
    - do: открыть страницу https://yandex.ru/turbo?stub=productpage/with-new-img-in-form.json
    - screenshot: внешний вид [plain]

  Внешний вид с бейджом безопасности:
    - do: открыть страницу https://yandex.ru/turbo?stub=productpage/product-1-with-safe.json&exp_flags=turboforms_endpoint=https://test-turbo-forms.common.yandex.ru/
    - screenshot: внешний вид соответствует скриншоту [plain]

files:
  - platform/components/ProductPage/__tests__/ProductPage@phone.hermione.js

v-team: Turbo

tags: 
  - e-commerce
  - no_assessors #раскатили новый дизайн на 100%

manager: tanzwuta

tlds: none
