feature: ProductPage
experiment: Просмотренные товары в карточке

specs:
  Внешний вид:
    - do: открыть https://yandex.ru/products/search?text=iphone
    - assert: |
        отобразилась страница с результатами поиска по товарам
        на странице больше 1 товара
    - do: кликнуть по первому товару на выдаче
    - assert: открылась страница с первым товаром
    - do: закрыть карточку с товаром
    - assert: |
        карточка с товаром скрылась
        отобразилась страница с результатами поиска по товарам
        на странице больше 1 товара
    - do: кликнуть по второму товару на выдаче
    - assert: открылась страница со вторым товаром
    - do: |
        внизу страницы с товаром находится блок "Вы смотрели"
        в блоке "Вы смотрели" отображается карточка первого товара
    - screenshot: внешний вид [first]
    - tech: карточка в блоке "Вы смотрели" содержит аттрибут target=_blank
    - assert: кликнуть по карточке в блоке "Вы смотрели"
    - do: открылась страница с первым товаром
    - do: |
        внизу страницы с товаром находится блок "Вы смотрели"
        в блоке "Вы смотрели" отображается карточка второго товара
    - screenshot: внешний вид [second]

v-team: goods

files:
  - src/pages/ProductPage/tests/exp/ProductPage_withRecent.touch.hermione.ts
