feature: ProductPage
experiment: Просмотренные товары в карточке

specs:
  Внешний вид:
    - params:
      exp_flags:
        - PRODUCTS_recent_items=1
    - do: открыть https://yandex.ru/products/search?text=iphone
    - assert: |
        отобразилась страница с результатами поиска по товарам
        на странице больше 1 товара
    - do: кликнуть по первому товару на выдаче
    - assert: открылась карточка с первым товаром
    - do: закрыть карточку с товаром
    - assert: |
        карточка с товаром скрылась
        отобразилась страница с результатами поиска по товарам
        на странице больше 1 товара
    - do: кликнуть по второму товару на выдаче
    - assert: |
        открылась карточка со вторым товаром
        внизу страницы с товаром находится блок "Вы смотрели"
        в блоке "Вы смотрели" отображается карточка первого товара
    - screenshot: внешний вид [first]
    - tech: карточка в блоке "Вы смотрели" содержит аттрибут target=_blank
    - assert: кликнуть по карточке в блоке "Вы смотрели"
    - do: открылась карточка с первым товаром в новой вкладке браузера
    - do: |
        внизу страницы с товаром находится блок "Вы смотрели"
        в блоке "Вы смотрели" отображается карточка второго товара
    - screenshot: внешний вид [second]

  Скролл в блоке:
    - params:
      exp_flags:
        - PRODUCTS_recent_items=1
    - do: открыть https://yandex.ru/products/search?text=футболка
    - assert: |
        отобразилась страница с результатами поиска по товарам
        на странице больше 6 товарова
    - do: поочередно открыть и затем закрыть с 1й по 5ю карточку
    - do: кликнуть на 6 карточку
    - assert: |
        в открывшейся карточке с товаром находится блок "Вы смотрели"
        в блоке "Вы смотрели" отображаются карточки товаров которые были открыты ранее
        справа в блоке есть кнопка со стрелкой для проскролла направо
    - do: нажать на кнопку со стрелкой направо
    - assert: |
        карточки в блоке "Вы смотрели" проскролились
        слева в блоке отобразилась кнопка со стрелкой налево для проскролла налево
    - screenshot: внешний вид [scrolled]

v-team: goods

files:
  - src/pages/ProductPage/tests/exp/ProductPage_withRecent.desktop.hermione.ts
