feature: Футер

specs:
  aliases:
    - &OpenSerpFooter
      - do: получить выдачу по запросу 'test'
      - do: проскроллить страницу до низа страницы
      - assert: на странице присутствует блок с ссылками на регион, ссылки на другие поисковики и другие
      - do: установить ширину окна браузера от 1350px

  Стандартные проверки:
    Цвет фокуса ссылки:
      - do: получить выдачу по запросу 'test'
      - do: нажимать клавишу Tab до тех пор, пока в фокусе не окажется переключатель региона в футере
      - assert: вокруг переключателя региона появилась желтая рамка
      - screenshot: внешний вид [region-change-focus]

    Отсутствие голубой рамки после клика в ссылку:
      - *OpenSerpFooter
      - do: нажать на ссылку 'Обратная связь'
      - assert: в отдельной вкладке происходит переход на feedback.yandex.ru
      - do: вернуться во вкладку с поиском
      - assert: вокруг ссылки 'Обратная связь' нет рамки
      - screenshot: внешний вид [feedback-focus-border]

    Отсутствие голубой рамки после клика в ссылку в попапе:
      - *OpenSerpFooter
      - do: кликнуть в кебаб-меню (три точки)
      - assert: открылся попап с ссылками
      - do: нажать на ссылку 'О компании'
      - assert: в отдельной вкладке происходит переход на yandex.ru/company
      - do: вернуться во вкладку с поиском
      - assert: в попапе вокруг ссылки 'О компании' нет рамки
      - screenshot: внешний вид [about-focus-border]

    Переключатель региона:
      Длинное название региона:
        - params:
            lr: '129232'
        - do: получить выдачу по запросу 'test'
        - do: проскроллить страницу до низа страницы
        - assert: в футере присутствует блок геолокации
        - do: выбрать регион с названием Кременчуг-Константиновское
        - assert: название региона в блоке геолокации обрывается троеточием
        - screenshot: внешний вид [long-region]

    Поиск в других системах:
      Переход на другие поисковые системы:
        - tlds: ru
        - *OpenSerpFooter
        - assert: в футере присутствует блок поиска в системах конкурентов
        - do: кликнуть по ссылке на Bing
        - assert: в отдельной вкладке происходит переход на www.bing.com c выдачей по запросу 'test'
        - do: |
            вернуться обратно на Yandex
            кликнуть по ссылке на Google
        - assert: в отдельной вкладке происходит переход на www.google.com c выдачей по запросу 'test'
        - do: |
            вернуться обратно на Yandex
            кликнуть по ссылке на Mail
        - assert: в отдельной вкладке происходит переход на go.mail.ru c выдачей по запросу 'test'

    Обратная связь и справка:
      Скрытие ссылок:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока обратной связи и справки
        - assert: в футере отсутствует блок обратной связи и справки
        - screenshot: внешний вид [plain]
      Ссылки в попапе:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока обратной связи и справки
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - assert: в попапе есть ссылка на обратную связь и справку
        - screenshot: внешний вид [plain]
      Отправка счетчиков в попапе для ссылки 'Обратная связь':
        - tags: counters
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока обратной связи и справки
        - do: кликнуть в кебаб-меню (три точки)
        - do: нажать на ссылку в попапе 'Обратная связь'
        - assert: в отдельной вкладке происходит переход на feedback.yandex.ru
        - tech: сработал счётчик path='/$page/$footer/feedback'
      Отправка счетчиков в попапе для ссылки 'Справка':
        - tags: counters
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока обратной связи и справки
        - do: кликнуть в кебаб-меню (три точки)
        - do: нажать на ссылку в попапе 'Справка'
        - assert: в отдельной вкладке происходит переход на yandex.ru/support/search
        - tech: сработал счётчик path='/$page/$footer/help'

    Настройки:
      Скрытие ссылки:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока настроек
        - assert: в футере отсутствует блок настроек
        - screenshot: внешний вид [plain]
      Ссылка в попапе:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока настроек
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - assert: в попапе есть ссылка на настройки
        - screenshot: внешний вид [plain]
      Отправка счетчиков в попапе:
        - tags: counters
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока настроек
        - do: кликнуть в кебаб-меню (три точки)
        - do: нажать на ссылку в попапе 'Настройки'
        - assert: в текущей вкладке происходит переход на yandex.ru/tune/search
        - tech: сработал счётчик path='/$page/$footer/settings'

    Семейный поиск:
      Выключен:
        - *OpenSerpFooter
        - assert: в футере присутствует блок семейного поиска
        - screenshot: внешний вид [family-mode-off]
      Включен:
        - do: получить выдачу по запросу 'порно'
        - do: проскроллить страницу до низа страницы
        - assert: на странице присутствует футер
        - do: установить ширину окна браузера от 1350px
        - assert: в футере присутствует блок семейного поиска
        - do: нажать на ссылку 'Включить семейный поиск'
        - assert: |
            произошла перезагрузка страницы
            семейный поиск включился
            выдача пустая
        - screenshot: внешний вид [family-mode-on]
      Отправка счетчиков:
        - tags: counters
        - *OpenSerpFooter
        - do: нажать на ссылку в попапе 'Включить семейный поиск'
        - assert: |
            произошла перезагрузка страницы
            семейный поиск включился
        - tech: сработал счётчик path='/$page/$footer/family-mode'
      Скрытие ссылки:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока семейного поиска
        - assert: в футере отсутствует блок семейного поиска
        - screenshot: внешний вид [plain]
      Ссылка в попапе:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока семейного поиска
        - do: кликнуть в кебаб (три точки)
        - assert: открылся попап с ссылками
        - assert: в попапе есть ссылка на включение/отключение семейного поиска
        - screenshot: внешний вид [plain]
      Отправка счетчиков в попапе:
        - tags: counters
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока семейного поиска
        - do: кликнуть в кебаб-меню (три точки)
        - do: нажать на ссылку в попапе 'Включить семейный поиск'
        - assert: |
            попап закрылся
            произошла перезагрузка страницы
            семейный поиск включился
        - tech: сработал счётчик path='/$page/$footer/family-mode'

    О компании:
      Внешний вид:
        - *OpenSerpFooter
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - assert: в ссылках есть 'О компании'
        - screenshot: внешний вид [about]
      Отправка счетчиков:
        - tags: counters
        - *OpenSerpFooter
        - do: кликнуть в кебаб-меню (три точки)
        - do: нажать на ссылку в попапе 'О компании'
        - assert: в отдельной вкладке происходит переход на yandex.ru/company
        - tech: сработал счётчик path='/$page/$footer/about'

    Вакансии:
      Внешний вид:
        - *OpenSerpFooter
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - assert: в ссылках есть 'Вакансии'
        - screenshot: внешний вид [vacancy]
      Отправка счетчиков:
        - tags: counters
        - *OpenSerpFooter
        - do: кликнуть в кебаб-меню (три точки)
        - do: нажать на ссылку в попапе 'Вакансии'
        - assert: в отдельной вкладке происходит переход на yandex.ru/jobs
        - tech: сработал счётчик path='/$page/$footer/vacancy'

    Кебаб-меню:
      Внешний вид:
        - *OpenSerpFooter
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - screenshot: внешний вид [plain]
      С семейным поиском:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока семейного поиска
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - assert: в попапе есть ссылка семейного поиска
        - screenshot: внешний вид [plain]
      С настройками:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока настроек
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - assert: в попапе есть ссылка настроек
        - screenshot: внешний вид [plain]
      С обратной связью и справкой:
        - *OpenSerpFooter
        - do: сменить ширину экрана до скрытия блока обратной связи и справки
        - do: кликнуть в кебаб-меню (три точки)
        - assert: открылся попап с ссылками
        - assert: в попапе есть ссылка обратной связи и справки
        - screenshot: внешний вид [plain]

  Широкий десктоп:
    - do: получить выдачу по запросу 'test'
    - do: проскроллить страницу до низа страницы
    - assert: на странице присутствует блок с ссылками на регион, ссылки на другие поисковики и другие
    - do: установить ширину окна браузера от 1600px
    - assert: иконка региона выровнена относительно края пейджера
    - screenshot: внешний вид [plain]

files:
  - src/features/SerpFooter/SerpFooter.test/SerpFooter@desktop.hermione.js

v-team: Beauty

tlds: all

tags:
  - react
  - footer
