feature: Настройки - шоу Алисы

files:
  - tests/hermione/suites/touch/legacy/settings-show/settings-show.hermione.js

specs:
  'Внешний вид':
    - automation: TODO
  'Раскрытие списков':
    - automation: TODO
  'Сохранение источников':
    - automation: TODO
