feature: Настройки - оплата и история операций

files:
  - tests/hermione/suites/touch/legacy/settings-payment-history/settings-payment-history.hermione.js

specs:
  'Без привязанных карт и покупок':
    - automation: TODO
  'С картой и покупками':
    - automation: TODO
