feature: Настройки Яндекс.Новостей

specs:
  позволяют добавить и удалить источник в Мои источники [manual]:
    - tags:
      - backend_news
      - brow_only
      - smoke_zen
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: тапнуть на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_170552.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: нажать на поле поиска 'Найти источник'
    - assert: происходит переход на страницу поиска для ввода названия источника https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_170722.png
    - do: ввести название 'РБК'
    - assert: появляется список с похожими названиями источников
    - do: тапнуть по звездочке возле источника 'РБК' (если звездочка уже прокрашена, выбрать другое название)
    - assert: отобржается всплывающая подсказка 'Добавлено в избранное', источник 'РБК' добавлен в список Мои источники, звездочка прокрашена желтым
    - do: закрыть модальное окно свайпом или тапом по галочке сверху и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источником 'РБК' в блоке Подробнее о событии
    - assert: точки возле источников 'РБК' прокрашены желтым
    - do: вернуться в 'Настройка источников' через аватарку пользователя и тапнуть на звездочку возле источника 'РБК'
    - assert: звездочка стала белой
    - do: закрыть модальное окно свайпом или тапом по галочке сверху и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источником 'РБК' в блоке Подробнее о событии
    - assert: точки возле источников 'РБК' и в заголовке отсуствуют

  позволяют добавить и удалить источник в Нежелательные источники [manual]:
    - tags:
      - backend_news
      - brow_only
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: тапнуть на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_170552.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: нажать на поле поиска 'Найти источник'
    - assert: происходит переход на страницу поиска для ввода названия источника https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_170722.png
    - do: ввести название 'Известия'
    - assert: появляется список с похожими названиями источников
    - do: нажать на кнопку добавления в нежелательное возле источника 'Известия' (если она уже прокрашена, выбрать другое название)
    - assert: отобржается всплывающая подсказка 'Добавлено в нежелательное', источник 'Известия' добавлен в список Мои источники,
        иконка прокрашена красным,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_171903.png
    - do: закрыть модальное окно свайпом или тапом по галочке сверху и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источником 'Известия' в блоке Подробнее о событии
    - assert: источники встречаются редко или не встречаются совсем
    - do: вернуться в 'Настройка источников' через аватарку пользователя
    - do: тапнуть на кнопку удаления из нежелательного возле источника 'Известия'
    - assert: кнопка возле источника изменилась на серую
    - do: обновить страницу
    - assert: автоматически раскрывается модальное окно настроек источников
    - do: в поле поиска ввести название 'Известия'
    - assert: в источнике 'Известия' иконка добавления в нежелательное покрашена в серый цвет

  позволяют добавить издательство в избранные источники [manual]:
    - tags:
        - backend_news
        - smoke_zen
    - do: зайти на сервис без авторизации
    - do: перейти по ссылке https://yandex.ru/news?favid=1048
    - assert: |
        раскрылось модальное окно с предложением авторизации для добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210629_171045.png
    - do: нажать на кнопку Войти и авторизоваться на сервисе
    - assert: |
        после авторизации автоматически раскрывается модальное окно с предложением добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210629_171137.png
    - do: тапнуть по кнопке Добавить источник
    - assert:
        появилась надпись - '«Коммерсантъ» в избранном'
        отображаются кнопки "Готово" и "Настроить другие источники"
    - do: кликнуть на кнопку "Готово"
    - do: тапнуть на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        раскрывается модальное окно настроек,
        источник из окна на шаге 1 добавлен в список Мои источники,
        звездочка возле источника прокрашена желтым
    - do: закрыть модальное окно свайпом или тапом по галочке сверху
    - do: перейти в ленту сюжетов, поискать сюжеты с этим источником в блоке Подробнее о событии
    - assert: точки возле источника из окна на шаге 1 прокрашены желтым

  позволяют открыть окно настройки избранных источников [manual]:
    - tags:
        - backend_news
    - do: зайти на сервис без авторизации
    - do: перейти по ссылке https://yandex.ru/news?favid=1048
    - assert: |
        раскрылось модальное окно с предложением авторизации для добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210629_171045.png
    - do: нажать на кнопку Войти и авторизоваться на сервисе
    - assert: |
        после авторизации автоматически раскрывается модальное окно с предложением добавления источника в избранные,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210629_171137.png
    - do: тапнуть по кнопке Добавить источник
    - assert:
        появилась надпись - '«Коммерсантъ» в избранном'
        отображаются кнопки "Готово" и "Настроить другие источники"
    - do: кликнуть по кнопке "Настроить другие источники"
    - assert: открылось модальное окно настройки источников https://jing.yandex-team.ru/files/kossakovskaya/2021-04-19_16-57-10.png

  позволяют добавлять и удалять избранные источники в настройках пользователя на нацдоменах [manual]:
    - tags:
#        - ua_suite
        - by_suite
        - backend_news
        - brow_only
        - smoke_zen
    - tlds:
#        - ua
        - by
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: перейти на страницу https://yandex.by/tune/geo и выставить город "Минск"
    - do: перейти на тестовый стенд
    - do: Перейти в любой новостной сюжет
    - do: тапнуть на аватарку пользователя, выбрать в меню 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
    - do: добавить несколько источников в избранные
    - assert: у источников отображаются желтые звездочки
    - do: добавить несколько источников в нежелательные
    - assert: у источников отображаются красные иконки
    - do: закрыть модальное окно свайпом или тапом по галочке сверху и обновить страницу
    - do: перейти в ленту сюжетов, поискать сюжеты с источниками, добавленными ранее в окне настроек, в блоке Подробнее о событии
    - assert: |
        точки возле источников из списка Мои источники прокрашены желтым,
        Нежелательные источники встречаются редко или не встречаются вовсе
    - do: вернуться в 'Настройка источников' через аватарку пользователя
    - do: добавить несколько источников из списка Нежелательные в список Мои источники
    - do: перейти в ленту сюжетов, поискать сюжеты с этими источниками
    - assert: точки возле источников прокрашены желтым

  можно открыть из меню трех точек авторизованному пользователю:
    - tags:
      - backend_news
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: тапнуть на меню трех точек внизу сюжета
    - assert: появляется поп-ап, содержащий пункты Настроить источники, Статистика сюжета
    - do: тапнуть на пункт 'Настройка источников'
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_170552.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: закрыть модальное окно тапнув на галочку
    - assert: модальное окно закрывается

  можно открыть из меню трех точек неавторизованному пользователю:
    - do: разлогиниться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: тапнуть на меню трех точек под аннотацией сюжета
    - assert: появляется поп-ап, содержащий пункты Настроить источники, Статистика сюжета
    - do: тапунть на пункт 'Настройка источников'
    - assert: |
        открылось модальное окно "Настройка источников" с кнопкой Войти,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_190945.png
    - do: закрыть модальное окно тапнув на галочку
    - assert: модальное окно закрывается

  позволяют авторизоваться через шторку избранного [manual]:
    - tags:
      - backend_news
      - smoke_zen
    - do: разлогиниться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: поскроллить до меню трех точек внизу сюжета (возле кнопки поделения) и тапнуть на меню трех точек
    - assert: появляется поп-ап, содержащий пункты Настроить источники, Статистика сюжета
    - do: тапнуть на пункт 'Настройка источников'
    - assert: |
        открылось модальное окно "Настройка источников" с кнопкой Войти,
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_190945.png
    - do: авторизоваться, нажав на кнопку Войти в модальном окне
    - assert: после авторизации открывается страница сюжета с открытым модальным окном настроек

  можно открыть по кнопке из блока Подробнее о событии:
    - tags:
      - backend_news
    - do: авторизоваться на сервисе Яндекс.Новости
    - do: перейти в любой неспортивный сюжет
    - do: нажать на кнопку настроек в блоке 'Подробнее о событии' (внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_162037.png)
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        отображаются описание, поле поиска 'Найти источник', список источников, напротив источников имеются кнопки добавления в избранные, и в нежелательные
        внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210412_170552.png (набор источников может отличаться, если источников нет, то отображается список источников на которые можно подписаться)
    - do: закрыть модальное окно тапнув на галочку
    - assert: модальное окно закрывается

  позволяют сохранять в избранное/нежелательное по одному источнику [manual]:
    - tags:
      - rareCase
    - do: авторизоваться на сервисе Яндекс.Новости (если еще не авторизованы)
    - do: перейти в любой неспортивный сюжет
    - do: нажать на кнопку настроек в блоке 'Подробнее о событии' (внешний вид https://jing.yandex-team.ru/files/an-smirn0v/shot_210414_162037.png)
    - assert: |
        раскрылось модальное окно настроек с анимацией,
        напротив источников имеются кнопки добавления в избранные, и в нежелательные
    - do: добавить 2-3 источника в избранное
    - assert: |
        в избранное добавляется только тот источник, напротив которого нажали на иконку избранного,
        иконки добавления в нежелательное окрашиваются в серый цвет, но при этом остаются кликабельными (внешний вид - https://jing.yandex-team.ru/files/vasekerka/2021-06-04_16-33-13.png)
    - do: добавить 2-3 источника в нежелательное
    - assert: |
        в нежелательное добавляется только тот источник, напротив которого нажали на иконку нежелательного,
        иконки добавления в избранное окрашиваются в серый цвет, но при этом остаются кликабельными (внешний вид - https://jing.yandex-team.ru/files/vasekerka/2021-06-04_16-33-31.png)

  показывают тултип для неавторизованного пользователя:
    - do: открыть любой сюжет в незалогине и с удаленной кукой nc
    - assert: тултип избранного показывается возле кнопки меню сюжета
    - do: кликнуть на крестик в тултипе
    - assert: тултип исчезает

  показывают тултип возле заголовка для авторизованного пользователя:
    - do: авторизоваться и открыть любой сюжет с избранным источником в заголовке
    - do: удалить куку nc
    - assert: тултип избранного показывается возле заголовка

files:
  - features/news/settings/settings.phone.hermione.js

qa-engineer: nightsonne

manager: mrwhite

tags:
  - neo
  - settings

tlds:
  - ru
  - by
  - kz
  - uz
  - ua
  - com
