feature: Одна организация
type: Похожие организации

specs-integration:
  beforeEach:
    - do: получить выдачу по запросу 'кафе пушкин' _ALTERNATIVE_SEARCH_QUERIES_
    - assert: на странице присутствует колдунщик организации
  Наличие элементов:
    - assert: |
        в карточке организации есть похожие организации,
        в похожих организациях есть тайтл,
        в похожих организациях есть список организаций,
  Открытие попапа организации:
    - do: кликнуть на первый элемент в похожих организациях
    - assert: открылся попап с карточкой организации

specs:
  На выдаче:
    Основные проверки в 1орге:
      - do: получить выдачу по запросу 'кафе пушкин' _ALTERNATIVE_SEARCH_QUERIES_
      - assert: |
          должна быть видна карточка организации в правой колонке
          должен быть виден блок похожих организаций
      - screenshot: внешний вид [plain]
      - do: кликнуть по стрелке справа
      - assert: блок с похожими организациями проскроллился вправо
      - tech: сработал счетчик path='/$page/$parallel/$result/composite/tabs/about/similar/scroller/arrow'
      - do: кликнуть по стрелке слева
      - assert: блок с похожими организациями проскроллился влево
      - tech: сработал счетчик path='/$page/$parallel/$result/composite/tabs/about/similar/scroller/arrow'
      - do: кликнуть по первому элементу блока
      - assert: появился попап с выбранной организацией
      - tech: сработал счетчик path='/$page/$parallel/$result/composite/tabs/about/similar/scroller/topic/topic'
      - assertMetrics: '*'
    Счетчик показа похожих в 1орг на выдаче:
      - do: получить выдачу по запросу 'кафе пушкин'
      - assert: |
          должна быть видна карточка организации в правой колонке
          должен быть виден блок похожих организаций
      - do: проскроллить карточку до похожих организаций
      - tech: сработал счетчик path='/$page/$parallel/$result/composite/tabs/about/similar/scroller/topic'
    Основные проверки в отеле:
      - do: получить выдачу по запросу 'отель рэдиссон славянская' _ALTERNATIVE_SEARCH_QUERIES_
      - assert: |
          должна быть видна карточка отеля в правой колонке
          должен быть виден блок похожих организаций
      - screenshot: внешний вид [hotel]
      - do: кликнуть по стрелке справа
      - assert: блок с похожими организациями проскроллился вправо
      - tech: сработал счетчик path='/$page/$parallel/$result/tabs/about/similar/scroller/arrow'
      - do: кликнуть по стрелке слева
      - assert: блок с похожими организациями проскроллился влево
      - tech: сработал счетчик path='/$page/$parallel/$result/tabs/about/similar/scroller/arrow'
      - do: кликнуть по первому элементу блока
      - assert: появился попап с выбранным отелем
      - tech: сработал счетчик path='/$page/$parallel/$result/tabs/about/similar/scroller/topic/topic'
      - assertMetrics: '*'
    Счетчик показа похожих в отелях на выдаче:
      - do: получить выдачу по запросу 'отель хаятт екатеринбург'
      - assert: |
          должна быть видна карточка отеля в правой колонке
          должен быть виден блок похожих организаций
      - do: проскроллить карточку до похожих организаций
      - tech: сработал счетчик path='/$page/$parallel/$result/tabs/about/similar/scroller/topic'
    Мало данных:
      - tags: no_assessors
      - params:
          lr: '54'
          oid: b:159282370813
          serp-reload-from: companies
      - do: получить выдачу по запросу 'Ипподром, Нижний Новгород'
      - assert: |
          должна быть видна карточка организации в правой колонке
          должен быть виден блок похожих организаций
      - do: кликнуть в тайтл первой похожей организации
      - assert: открылся большой попап с информацией об организации
  В попапе:
    - do: получить выдачу по запросу 'lets rock бар' _ALTERNATIVE_SEARCH_QUERIES_
    - assert: должна быть видна карточка организации в правой колонке
    - do: кликнуть в первую похожую организацию
    - assert: открылся большой попап
    - assert: открылся таб с информацией об организации
    - screenshot: внешний вид блока [popup]
    - do: кликнуть по первому элементу блока
    - assert: попап перезагрузился, появилась выбранная организация в попапе
    - tech: сработал счетчик path='/$subresult/company/tabs/about/similar/scroller/topic/topic'
  Счетчик показа похожих в попапе:
    - do: получить выдачу по запросу 'кафе пушкин'
    - assert: |
        должна быть видна карточка организации в правой колонке
        должен быть виден блок похожих организаций
    - do: кликнуть в титул Отзывы
    - assert: открылся большой попап с табом отзывов
    - do: кликнуть в таб Главное
    - assert: открылся таб с информацией об организации
    - do: проскроллить карточку до похожих организаций
    - tech: сработал счетчик path='/$subresult/company/tabs/about/similar/scroller/topic'
  Организация без отзывов:
    - do: получить выдачу по запросу 'istanbul havalimanı аэропорт istanbulkart'
    - assert: |
        должна быть видна карточка организации в правой колонке
        должен быть виден блок похожих организаций
    - do: кликнуть по первому элементу блока похожих организаций
    - assert: появился попап с выбранной организацией

tlds: all

v-team: VanillaGeo

files:
  - src/features/Companies/Companies.features/SimilarCompanies/SimilarCompanies.test/SimilarCompanies@desktop.hermione.js
  - src/features/Companies/Companies.features/SimilarCompanies/SimilarCompanies.test/SimilarCompanies@desktop.hermione.e2e.js

counter: /$page/$parallel/$result//similar/scroller/topic/topic

tags:
  - react
  - hasE2E
  - geo
  - geo_one_org
  - geo_one_org_similar
