feature: Поезда
type: Выбор мест
description: >-
  Кейс проверяет корректность информации и верстку на странице выбора мест в
  блоке с информацией о поезде:

  ![image](https://jing.yandex-team.ru/files/arhey/2022-01-14T07:52:52Z.eac2382.png)

  Перейти на вкладку ЖД билеты

  Открыта произвольная выдача, например, Москва - Санкт-Петербург на завтра
specs:
  'ЖД: Тач: блок с информацией о поезде на странице выбора мест':
    - do: Тапнуть "выбрать место" у поезда с наименованием (например, фирменный)
    - assert: |-
        Открывается страница выбора мест.
        На странице сверху есть блок с информацией о поезде
        В нем указано:
        - Города отправления и прибытия
        - Дата поездки
        - Номер поезда, название (если есть), города следования поезда
        - Время отправления/прибытия, время в пути, приписка "Время местное"
        - Станции отправления/прибытия

files:
    - tests/touch/trains/places/trains-places-train-info-touch.hermione.ts

Функциональность: Разное по странице выбора мест
Устройство: Тач
Страница: Выбор мест
Сервис: ЖД
Тестирование асессорами: Да
Окружение:
  - Production
  - Testing
Tag: Smoke
Автор: shenfeld
