feature: Колдунщик переводов

specs:
  Внешний вид с пустым полем ввода:
    - tags: no_assessors
    - do: получить выдачу по запросу 'переводчик онлайн'
    - assert: должен появиться пустой колдунщик переводов
    - screenshot: переводчик [empty]
  Проверка внешнего вида фактового к-ка:
    - tags: no_assessors
    - params:
        foreverdata: '3127763789'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: должен появиться фактовый колдунщик переводов
    - screenshot: переводчик [fact]
  Проверка внешнего вида фактового к-ка для перевода из словаря:
    - tags: no_assessors
    - params:
        foreverdata: '3122732455'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: должен появиться фактовый колдунщик переводов c переводом 'Облако'
    - screenshot: переводчик [fact-dictionary]
  Не показывается спиннер, при потере фокуса у инпута, если текст не поменялся:
    - tags: no_assessors
    - do: получить выдачу по запросу 'кот перевод'
    - do: кликнуть в поле перевода
    - do: кликнуть в свободное место на странице
    - assert: спиннер не появился
  Если перевод не пришел на сервере:
    - tags: no_assessors
    - do: получить выдачу по запросу 'неглиже перевод на татарский язык'
    - assert: должен появиться пустой колдунщик переводов
    - assert: через некоторое время должен появится перевод
    - screenshot: переводчик [plain]
  Если пришел новый неизвестный язык в пустой к-к:
    - tags: no_assessors
    - params:
        foreverdata: '3122732455'
    - do: получить выдачу по запросу 'foreverdata'
    - assert: в селектах не должно быть undefined
    - screenshot: левый селект [unknownEmptySource]
    - screenshot: правый селект [unknownEmptyTarget]
  Автоопределение языка:
    - tags: no_assessors
    - do: получить выдачу по запросу 'белиссимо с итальянского'
    - assert: должен появиться колдунщик переводов
    - tech: сработали счётчики смены языка
    - tech: сработал счётчик перевода
  Проверка на доступность:
    - do: получить выдачу по запросу 'кот перевод'
    - assert: появляется колдунщик переводов
    - tech: |
        у свопа языков должен быть атрибуты role='button', tabindex="0"
        у озвучки исходного текста должен быть атрибуты role='button', tabindex="0"
        у озвучки перевода должен быть атрибуты role='button', tabindex="0"
        у кнопки копирования должен быть атрибуты role='button', tabindex="0"
        у селекта исходного языка должен быть атрибуты role='button', tabindex="0"
        у селекта языка перевода должен быть атрибуты role='button', tabindex="0"
  Общие проверки:
    beforeEach:
      - do: получить выдачу по запросу 'перевод'
      - assert: появляется колдунщик переводов с пустым полем ввода текста
    Копирование:
      - browsers:
          notFor:
            - 'ios-safari-7-pad'
            - 'ios-safari-8-pad'
            - 'ios-safari-9-pad'
            - 'iphone'
      - tags:
          - smoke_extended
          - no_assessors
      - do: вставить в поле ввода слово 'get'
      - assert: появляется результат с переводом
      - do: кликнуть на кнопку копирования (кнопка в правой части нижнего поля в виде квадратика)
      - tech: проверить динамический счётчик на кнопке копирования
    Вставка текста из буфера:
      - tags:
        - smoke_extended
        - no_assessors
      - do: вставить из буфера в поле ввода колдунщика текст 'ハイ'
      - assert: измениться язык перевода на 'Японский'
      - assert: результат с переводом появляется рядом(снизу или сбоку) с полем ввода текста
      - screenshot: переводчик [plain]
    Неизвестный язык при автодетекте:
      - tags: no_assessors
      - do: вставить в поле ввода ダイレクト
      - do: |
          с помощью Charles подменить значение в поле lang
          в ответе с https://translate.yandex.net/api/v1/tr.json/detect?... на 'new_lang'
      - assert: язык в левом селекте должен остаться прежним
    Очистка поля ввода крестиком:
      - tags: no_assessors
      - do: вставить в поле ввода слово 'search'
      - do: нажать на иконку крестика в поле ввода
      - tech: сработал динамический счётчик очистки поля ввода
      - assert: поле ввода становится пустым
    Проверки с контролами:
      beforeEach:
        - do: вставить в поле ввода слово 'friend'
        - assert: появляется результат с переводом слова
      При смене языков местами значение инпута изменяется:
        - tags: no_assessors
        - do: кликнуть по кнопке смены языков
        - tech: проверить динамический счётчик в кнопке смены языков местами
        - assert: результат с переводом обновляется
    Смена направления при плохом интернете:
      - tags: no_assessors
      - do: отключить интернет
      - do: вставить в поле ввода слово 'test'
      - do: кликнуть по кнопке смены языков
      - tech: сработал динамический счётчик смены языков местами
      - assert: в поле ввода останется 'test'
  Проверки с текстом:
    Повторный перевод (пустой колдунщик):
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевод онлайн'
      - assert: появляется колдунщик переводов
      - do: вставить в поле ввода слово 'test'
      - assert: появляется результат со словарной статьей
      - do: очистить поле ввода
      - do: вставить в поле ввода слово 'test'
      - assert: появляется результат со словарной статьей
    Повторный перевод другого слова:
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевод онлайн'
      - assert: появляется колдунщик переводов
      - do: вставить в поле ввода слово 'test'
      - assert: появляется результат со словарной статьей
      - do: очистить поле ввода
      - do: вставить в поле ввода слово 'cat'
      - assert: появляется результат со словарной статьей перевода последнего запроса
    Повторный перевод (заполненный колдунщик):
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевести test'
      - assert: появляется колдунщик переводов со словарной статьей
      - do: очистить поле ввода
      - do: снова вставить в поле ввода слово 'test'
      - assert: появляется результат со словарной статьей
    Повторный перевод (колдунщик без словаря):
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевести test get'
      - assert: появляется колдунщик переводов
      - do: вставить в поле ввода слово 'test'
      - assert: появляется результат со словарной статьей
      - do: снова вставить в поле ввода слово 'test get'
      - assert: появляется перевод
    Перевод берется из поля translation:
      - tags: no_assessors
      - params:
          foreverdata: '652258663'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: рядом с полем ввода колдунщика сразу появляется перевод и словарная статья
      - assert: результат перевода - 'отлично сработано'
    Перевод возьмется из ручки переводчика, а не из словаря:
      - tags: no_assessors
      - params:
          foreverdata: '1212852229'
      - do: получить выдачу по запросу 'foreverdata'
      - assert: рядом с полем ввода колдунщика сразу появляется перевод
      - assert: результат перевода - 'отлично сработано'
  Проверка технических кликов при свопе:
    beforeEach:
      - do: вставить в поле ввода слово 'кот'
      - assert: появляется результат с переводом слова
    При смене языков местами нет повторений технических кликов:
      - tags: no_assessors
      - do: кликнуть по кнопке смены языков
      - tech: проверить динамический счётчик в кнопке смены языков местами
      - tech: проверить технические счётчики смены языков
      - assert: результат с переводом обновляется
  Локализация в словарной статье:
    tlds: [ru, com.tr]
    langs: tr, uk, be, kk
    язык uk:
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевод с английского на русский'
      - assert: появляется колдунщик переводов
      - do: вставить в поле ввода слово 'cat'
      - assert: появляется результат со словарной статьей
      - do: убрать фокус с поля ввода
      - screenshot: части речи в словарной статье правильно локализованы [plain]
    язык be:
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевод с английского на русский'
      - assert: появляется колдунщик переводов
      - do: вставить в поле ввода слово 'cat'
      - assert: появляется результат со словарной статьей
      - do: убрать фокус с поля ввода
      - screenshot: части речи в словарной статье правильно локализованы [plain]
    язык tr:
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевод с английского на русский'
      - assert: появляется колдунщик переводов
      - do: вставить в поле ввода слово 'cat'
      - assert: появляется результат со словарной статьей
      - do: убрать фокус с поля ввода
      - screenshot: части речи в словарной статье правильно локализованы [plain]
    язык kk:
      - tags: no_assessors
      - do: получить выдачу по запросу 'перевод с английского на русский'
      - assert: появляется колдунщик переводов
      - do: вставить в поле ввода слово 'cat'
      - assert: появляется результат со словарной статьей
      - do: убрать фокус с поля ввода
      - screenshot: части речи в словарной статье правильно локализованы [plain]
  Озвучка:
    Некликабельный контрол для неподдерживаемых языков:
      - tags: no_assessors
      - do: выставить направление перевода Болгарский-Македонский
      - do: вставить в поле ввода текста фразу 'Здравей, свят'
      - assert:
          иконка динамика в поле ввода текста перечеркнута и не кликабельна
          иконка динамика в поле перевода перечеркнута и не кликабельна
  Метрики:
    beforeEach:
      - do: получить выдачу по запросу 'кот перевод'
      - tech: проверить метрики
    Клик в крестик:
      - tags: no_assessors
      - do: кликнуть в крестик
      - tech: проверить метрики
    Клик в инпут + очистка:
      - tags: no_assessors
      - do: кликнуть в инпут, потом очистить крестиком
      - tech: проверить метрики
    Клик в выдачу перевода:
      - tags: no_assessors
      - do: Кликнуть в результат перевода
      - tech: проверить метрики
    Фактовый к-к:
      beforeEach:
        - do: получить выдачу по запросу 'foreverdata'
      Клик в синюю ссылку:
        - tags: no_assessors
        - params:
              foreverdata: '3127763789'
        - do: Кликнуть в синюю ссылку
        - tech: проверить метрики
      Клик в ответ:
        - tags: no_assessors
        - params:
            foreverdata: '3127763789'
        - do: Кликнуть в текст ответа
        - tech: проверить метрики
    Озвучание перевода:
      - tags: no_assessors
      - do: кликнуть в кнопку озвучания перевода
      - tech: проверить метрики
    Озвучание введенного текста:
      - tags: no_assessors
      - do: кликнуть в кнопку озвучания введенного текста
      - tech: проверить метрики
    Копирование перевода:
      - tags: no_assessors
      - do: кликнуть в кнопку копирования перевода
      - tech: проверить метрики

  Проверки в Турции:
    params:
      lr: '11508'
      l10n: 'tr'
      tld: 'com.tr'
    beforeEach:
      - do: получить выдачу по запросу 'cat çeviri'
      - assert: должен появиться колдунщик переводов
    При вводе слова 'dog' появляется результат с переводом:
      - tags: no_assessors
      - do: кликнуть в крестик
      - do: написать в поле ввода колдунщика слово 'dog'
      - assert: результат с переводом появляется рядом(снизу или сбоку) с полем ввода текста
    При смене языков местами значение инпута изменяется:
      - tags: no_assessors
      - do: кликнуть по кнопке смены языков
      - tech: проверить динамический счётчик в кнопке смены языков местами
      - assert: результат с переводом обновляется

specs-integration:
  Проверка заполненного к-ка:
    - tags:
      - smoke
      - pp_new_core
    - do: получить выдачу по запросу 'кот перевод'
    - assert: должен появиться колдунщик переводов
    - counter: /$page/$main/$result[@wizard_name="translate"]
  При вводе слова 'test' появляется результат с переводом:
    - tags:
      - smoke
      - smoke_extended
      - pp_new_core
    - do: ввести запрос "перевод" в поисковую строку и получить колдунщик перевода
    - do: вставить в поле ввода колдунщика слово 'test'
    - assert: результат с переводом появляется рядом(снизу или сбоку) с полем ввода текста
    - counter: /$page/$main/$result[@wizard_name="translate"]

files:
  - src/features/Translate/Translate.test/Translate@common.hermione.js
  - src/features/Translate/Translate.test/Translate@common.hermione.e2e.js

counter: /$page/$main/$result[@wizard_name="translate"]

v-team: Translations_misspell

tlds: all
