feature: Настройки профиля пользователя

specs:

    Профиль пользователя который состоит в организации[manual]:
        - automation:
        - do: Авторизоваться аккаунтом состоящим в организации
        - assert: Авторизация прошла успешно
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: |
              Открывается окно настроек
              Под аватаркой и именем пользователя находится секция "Пространства" для переключения организаций
        - do: Обновить страницу
        - assert: На экране настроек активна та же организация, которая была активна до обновления страницы
    
    Профиль пользователя который не состоит в организации[manual]:
        - automation:
        - do: Авторизоваться аккаунтом не состоящим в организации
        - assert: Авторизация прошла успешно
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: |
              Открывается окно настроек
              Под аватаркой и именем пользователя НЕТ секции "Пространства" для переключения организаций
        - do: Обновить страницу
        - assert: В настройках секция "Пространства" НЕ отображается
    
    Профиль пользователя с несколькими организациями[manual]:
        - automation:
        - do: Авторизоваться аккаунтом состоящим в организации
        - assert: Авторизация прошла успешно
        - do: Открыть список чатов через нижний тулбар по кнопке Чаты, если открыта другая вкладка.
        - assert: Открывается окно списка чатов.
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: |
              Открывается окно настроек.
              Под аватаркой и именем пользователя находится секция "Пространства" для переключения организаций
        - do: Посмотреть на секцию "Пространства"
        - assert: Организации отображаются в следующем порядке ООО "..." ; ООО "..." ; Личные чаты
        - do: Обновить страницу
        - assert: Секция "Пространства" отображается, находимся в той организации которая была активна до обновления страницы
    
    Выбор пространства[manual]:
        - automation:
        - do: Авторизоваться аккаунтом состоящим в организации
        - assert: Авторизация прошла успешно
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: |
              Открывается окно настроек
              Под аватаркой и именем пользователя находится секция "Пространства" для переключения организаций
        - do: Посмотреть на выбранное по умолчанию пространство
        - assert: По умолчанию в секции "Пространства" выбрано пространство "Организации". список чатов соответствует выбранному пространству
        - do: Выбрать пространство "Личные чаты"
        - assert: В секции "Пространства" выбрано пространство "Личные чаты"
        - do: Вернуться в список чатов 
        - assert: Открывается список чатов, в списке отображаются чаты, относящиеся к выбранному пространству.
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: |
              Открывается окно настроек
              Под аватаркой и именем пользователя находится секция "Пространства" для переключения организаций
        - do: Выбрать пространство "Организации"
        - assert: В секции "Пространства" выбрано пространство "Организации". Список чатов соответствует выбранному пространству
        - do: Вернуться в список чатов
        - assert: Открывается список чатов, в списке отображаются чаты созданные и относящиеся к выбранному пространству.
    
    По умолчанию после чистой установки в секции "Пространства" выбрано пространство "организации" если пользователь состоит в организации[manual]:
        - automation:
        - do: Авторизоваться аккаунтом состоящим в организации во вкладке икогнито
        - assert: Авторизация прошла успешно
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: |
              Открывается окно настроек
              Под аватаркой и именем пользователя находится секция "Пространства" для переключения организаций
              В секции "пространства" по умолчанию выбрана "организация"

    Карточка пользователя организации с доменом @yandex.ru (внешний вид карточки)[manual]:
        - automation:
        - description: |
              Для прохождения данного кейса необходимы пользователь А и Б с аккаунтами @yandex.ru состоящие в организации
              У пользователя А в списке чатов есть:
              Приватный чат с пользователем Б
              Канал где он админ, а пользователь Б подписчик. В чате есть сообщение отправленное пользователем Б
              Групповой чат где состоит пользователь Б
        - do: Авторизоваться аккаунтом А 
        - assert: Авторизация прошла успешно
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: Открывается экран настроек пользователя
        - do: Проверить, что в разделе пространства выбрана организация, в которой состоит пользователь. Если нет, выбрать организацию
        - assert: Организация выбрана
        - do: Вернуться в список чатов и открыть **ПРИВАТНЫЙ ЧАТ** из Description
        - assert: Открывается окно чата
        - do: Нажать на шапку чата
        - assert: Открывается окно информации о пользователе
        - do: Проверить наличие секции "Дополнительно" и пунктов:- подразделение- почта 
        - assert: Нужная секция и ее разделы присутствуют.Информация совпадает с информацией в админке 360
        - do: Вернуться на список чатов и открыть **ГРУППОВОЙ ЧАТ** с пользователем Б из Description
        - assert: Чат открыт
        - do: Тапнуть на аватар пользователя Б, рядом с отправленным им сообщением 
        - assert: Открывается окноОткрывается окно**IOS:** Информация о контакте**Android:** Информация о пользователе
        - do: Проверить наличие секции "Дополнительно", пунктов подразделение и почта 
        - assert: Нужная секция и ее разделы присутствуют.Информация совпадает с информацией в админке 360
        - do: Вернуться на список чатов и открыть КАНАЛ с пользователем Б из Description
        - assert: Канал открыт
        - do: Тапнуть по шапке канала и перейти в раздел "Подписчики и администраторы"
        - assert: Раздел открыт
        - do: Тапнуть на пользователя Б
        - assert: Карточка пользователя открыта
        - do: Проверить наличие секции "Дополнительно" и пунктов подразделение и почта 
        - assert: Нужная секция и ее разделы присутствуют. Информация совпадает с информацией в админке 360
    
    Карточка пользователя организации с доменом организации (внешний вид карточки)[manual]:
        - automation:
        - description: |
              Для прохождения данного кейса необходимы пользователь А и Б, состоящие в организации. 
              Пользователь Б обязательно с доменом организации. Если нет такого пользователя, его можно создать в организации https://admin.yandex.ru
              У пользователя А в списке чатов есть:
              Приватный чат с пользователем Б
              Канал где он админ, а пользователь Б подписчик. В чате есть сообщение отправленное пользователем Б
              Групповой чат где состоит пользователь Б
        - do: Авторизоваться аккаунтом А состоящим в организации
        - assert: Авторизация прошла успешно
        - do: Нажать на кнопку настроек в верхнем правом углу списка чатов
        - assert: Открывается экран настроек пользователя
        - do: Проверить, что в разделе пространства выбрана организация, в которой состоит пользователь. Если нет, выбрать организацию
        - assert: Организация выбрана
        - do: Вернуться в список чатов и открыть ПРИВАТНЫЙ ЧАТ из Description
        - assert: Открывается окно чата
        - do: Нажать на шапку чата
        - assert: Открывается окно с информацией о пользователе
        - do: Проверить наличие секции "Дополнительно" и пунктов подразделение и  почта 
        - assert: Нужная секция и ее разделы присутствуют. Информация совпадает с информацией в админке 360
        - do: Вернуться на список чатов и открыть ГРУППОВОЙ ЧА с пользователем Б из Description
        - assert: Чат открыт
        - do: Тапнуть на аватар пользователя Б, рядом с отправленным им сообщением 
        - assert: Открывается окно с информацией о пользователе
        - do: Проверить наличие секции "Дополнительно" и пунктов подразделение и почта 
        - assert: Нужная секция и ее разделы присутствуют. Информация совпадает с информацией в админке 360
        - do: Вернуться на список чатов и открыть КАНАЛ с пользователем Б из Description
        - assert: Канал открыт
        - do: Тапнуть по шапке канала и перейти в раздел "Подписчики"
        - assert: Раздел открыт
        - do: Тапнуть на пользователя Б
        - assert: Карточка пользователя открыта
        - do: Проверить наличие секции "Дополнительно" и пунктов подразделение и почта 
        - assert: Нужная секция и ее разделы присутствуют.Информация совпадает с информацией в админке 360
    
files: []

v-team: Chat

tlds: ru

tags:
    - yamb
