feature: Я.Плюс
type: Проверка наличия кнопки Я.Плюс в шапке

tlds: [kz, ru, by]

specs:
  beforeEach:
    - do: авторизоваться на портале Яндекс с логином 'yndx-lego-test-user01' и паролем 'Z9yx.6v0Q'
    - do: получить выдачу по запросу 'плюс'
    - assert: в шапке присутствует кнопка 'Плюс' с надписью 'Будьте в плюсе' рядом с ней (для планшетов нужно повернуть устройcтво в горизонтальную ориентацию для отображения "Будьте в плюсе")
    - screenshot: пример внешнего вида (надпись может быть на другом языке в зависимости от локализации) [https://jing.yandex-team.ru/files/likharad-m/Monosnap_file_z3mh4.png]
  Наличие кнопки Я.Плюс в шапке на широком экране tld=ru l10n=ru lr=213:
    - tlds: ru
    - langs: ru
    - params:
        lr: '213'
    - assert: ссылка 'Будьте в плюсе' ведёт на промо-страницу Яндекс.Плюс
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки в шапке на узком экране tld=ru l10n=ru lr=213:
    - tlds: ru
    - langs: ru
    - params:
        lr: '213'
    - do: уменьшить окно браузера или перевернуть устройство, если это планшет
    - assert: в шапке присутствует кнопка 'Плюс', надпись 'Будьте в плюсе' пропала
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - screenshot: пример внешнего вида [https://jing.yandex-team.ru/files/likharad-m/Monosnap_file_bxsbc.png]
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки Я.Плюс в шапке на широком экране tld=by l10n=be lr=157:
    - tlds: by
    - langs: be
    - params:
        lr: '157'
    - assert: ссылка 'Будьте в плюсе' ведёт на промо-страницу Яндекс.Плюс
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки в шапке на узком экране tld=by l10n=be lr=157:
    - tlds: by
    - langs: be
    - params:
        lr: '157'
    - do: уменьшить окно браузера или перевернуть устройство, если это планшет
    - assert: в шапке присутствует кнопка 'Плюс', надпись 'Будьте в плюсе' пропала
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - screenshot: пример внешнего вида [https://jing.yandex-team.ru/files/likharad-m/Monosnap_file_bxsbc.png]
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки Я.Плюс в шапке на широком экране tld=kz l10n=kk lr=163:
    - tlds: kz
    - langs: kk
    - params:
        lr: '163'
    - assert: ссылка 'Будьте в плюсе' ведёт на промо-страницу Яндекс.Плюс
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки в шапке на узком экране tld=kz l10n=kk lr=163:
    - tlds: kz
    - langs: kk
    - params:
        lr: '163'
    - do: уменьшить окно браузера или перевернуть устройство, если это планшет
    - assert: в шапке присутствует кнопка 'Плюс', надпись 'Будьте в плюсе' пропала
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - screenshot: пример внешнего вида [https://jing.yandex-team.ru/files/likharad-m/Monosnap_file_bxsbc.png]
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки Я.Плюс в шапке на широком экране tld=uz l10n=uz lr=10335:
    - tlds: uz
    - langs: uz
    - params:
        lr: '10335'
    - assert: ссылка 'Будьте в плюсе' ведёт на промо-страницу Яндекс.Плюс
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки в шапке на узком экране tld=uz l10n=uz lr=10335:
    - tlds: uz
    - langs: uz
    - params:
        lr: '10335'
    - do: уменьшить окно браузера или перевернуть устройство, если это планшет
    - assert: в шапке присутствует кнопка 'Плюс', надпись 'Будьте в плюсе' пропала
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - screenshot: пример внешнего вида [https://jing.yandex-team.ru/files/likharad-m/Monosnap_file_bxsbc.png]
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки Я.Плюс в шапке на широком экране tld=ru l10n=ru lr=10313:
    - tlds: ru
    - langs: ru
    - params:
        lr: '10313'
    - assert: ссылка 'Будьте в плюсе' ведёт на промо-страницу Яндекс.Плюс
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'
  Наличие кнопки в шапке на узком экране tld=ru l10n=ru lr=10313:
    - tlds: ru
    - langs: ru
    - params:
        lr: '10313'
    - do: уменьшить окно браузера или перевернуть устройство, если это планшет
    - assert: в шапке присутствует кнопка 'Плюс', надпись 'Будьте в плюсе' пропала
    - do: кликнуть на кнопку
    - assert: открылась промо-страница Яндекс.Плюс
    - screenshot: пример внешнего вида [https://jing.yandex-team.ru/files/likharad-m/Monosnap_file_bxsbc.png]
    - tech: ссылка содержит все utm-метки и они соответствуют платформе
    - tech: на ссылке 'Будьте в плюсе' корректный счётчик '/head/plus/on'

files:
  - features/deskpad/yaplus/yaplus-in-header.hermione.js

v-team: Lego

tags:
  - yaplus
  - reviewed
  - skip_e2e_check
  - smoke
  - smoke_extended

counter: /head/plus/on
